import { SEED_HUNTER, SEED_POSTER } from "./bounty-types";
import type { CountryId } from "./types";

type SeedSub = { hunter: string; name: string; proof: string; status: "pending" | "accepted" | "rejected" };

export type SeedBounty = {
  slug: string;
  posterName: string;
  title: string;
  titleSw: string;
  description: string;
  deliverables: string;
  projectSlug: string | null;
  county: string | null;
  country?: CountryId;
  rewardKes: number;
  status: "open" | "paid" | "closed";
  days: number;
  subs: SeedSub[];
};

export const SEED_BOUNTIES: SeedBounty[] = [
  {
    slug: "lurambi-grade-stop",
    posterName: "Civic desk · Kakamega",
    title: "Photograph the Lurambi grade-stop",
    titleSw: "Piga picha paisho la barabara Lurambi",
    description:
      "Paper says 4.2 km of gravel was paid in full. Walk the gazetted alignment. Show where the grade ends.",
    deliverables:
      "Three photographs (start, stop, culvert rings). GPS on the public alignment. A 280-character note. No faces.",
    projectSlug: "lurambi-feeder-road",
    county: "Kakamega",
    rewardKes: 12_000,
    status: "open",
    days: 18,
    subs: [
      { hunter: SEED_HUNTER, name: "Monitor 04", proof: "Grade ends at 700 m. Culvert rings in the grass. Hash on phone.", status: "pending" },
      { hunter: "seed-hunter-b", name: "Monitor 11", proof: "Walked from the market junction. Footpath after the first drift.", status: "pending" },
    ],
  },
  {
    slug: "kakuma-empty-plot",
    posterName: "Health watch · Turkana",
    title: "Confirm Kakuma staff houses: empty plot or foundations",
    titleSw: "Thibitisha nyumba za Kakuma: kiwanja tupu au misingi",
    description:
      "Four units were certified complete. Neighbours say the contractor never camped. Need an independent visit.",
    deliverables: "GPS at the plot beside the existing clinic. Photograph of the ground. Note on foundations: none / started / built.",
    projectSlug: "kakuma-staff-houses",
    county: "Turkana",
    rewardKes: 9_000,
    status: "open",
    days: 11,
    subs: [{ hunter: SEED_HUNTER, name: "Monitor 04", proof: "Empty plot. No foundations. Clinic still the only building.", status: "pending" }],
  },
  {
    slug: "kitui-dam-scrape",
    posterName: "Water user group · Kisasi",
    title: "Walk Kitui Zone 4 earth dam: spillway yes or no",
    titleSw: "Tembea bwawa la Kitui Eneo 4: njia ya mafuriko ndiyo au hapana",
    description: "Final certificate paid. Livestock still walk 6 km in the dry season. We need the scrape measured against a spillway.",
    deliverables: "Photograph of the basin. Photograph of any spillway or tap stand. GPS. Short note.",
    projectSlug: "kitui-earth-dam",
    county: "Kitui",
    rewardKes: 8_000,
    status: "open",
    days: 9,
    subs: [],
  },
  {
    slug: "kayole-poles-after-dark",
    posterName: "Market lane committee",
    title: "Count standing Kayole Lot B poles after dark",
    titleSw: "Hesabu nguzo za Kayole Kundi B baada ya giza",
    description: "Forty poles on paper. Count what is standing, what has a lamp, and which are dark on the market lane.",
    deliverables: "Count of poles, lamps, dark poles. One photograph of the market lane. GPS at two ends.",
    projectSlug: "kayole-lighting-b",
    county: "Nairobi",
    rewardKes: 4_500,
    status: "open",
    days: 6,
    subs: [
      { hunter: "seed-hunter-c", name: "Monitor 19", proof: "22 poles standing, 12 dark, none on the market lane.", status: "pending" },
    ],
  },
  {
    slug: "langata-borehole-pad",
    posterName: "Ward water table",
    title: "Lang'ata borehole Phase II: pad only, or pump and tank",
    titleSw: "Kisima Lang'ata Awamu II: slab tu, au pampu na tanki",
    description: "Payment certificate 3 of 3 marked complete. We need a current photograph of the slab.",
    deliverables: "Photograph of the pad. Note: pump yes/no, tank yes/no. GPS.",
    projectSlug: "langata-borehole-ii",
    county: "Nairobi",
    rewardKes: 6_000,
    status: "open",
    days: 21,
    subs: [],
  },
  {
    slug: "malindi-latrine-roof",
    posterName: "School board clerk (demo)",
    title: "Malindi sanitation block: roof, doors, lined pit?",
    titleSw: "Kizuizi cha usafi Malindi: paa, milango, shimo?",
    description: "Marked substantially complete. Children still use the old block. Confirm what is usable.",
    deliverables: "Three photographs. Note on roof, doors, pit lining. GPS at the school gate.",
    projectSlug: "malindi-sanitation-block",
    county: "Kilifi",
    rewardKes: 3_000,
    status: "open",
    days: 14,
    subs: [],
  },
  {
    slug: "nyalenda-shades-wing",
    posterName: "Traders' welfare (demo)",
    title: "Nyalenda market: how many wings still open sky",
    titleSw: "Soko Nyalenda: pande ngapi bado ni wazi",
    description: "90 percent disbursed. Count steel columns vs open stalls. Ablution slab: usable or not.",
    deliverables: "Wing count. Photograph of the open sky. Photograph of the ablution slab.",
    projectSlug: "nyalenda-market-shades",
    county: "Kisumu",
    rewardKes: 5_500,
    status: "open",
    days: 16,
    subs: [{ hunter: "seed-hunter-d", name: "Monitor 07", proof: "One wing has columns. Two wings open sky. Ablution is a slab.", status: "pending" }],
  },
  {
    slug: "likoni-ecd-in-use",
    posterName: "Coast education desk",
    title: "Likoni ECD: is the twin classroom in the timetable",
    titleSw: "ECD Likoni: je madarasa mapacha yako kwenye ratiba",
    description: "Certificate of completion January 2024. Independent visits should agree the building is in use.",
    deliverables: "Photograph of the building in use (no children's faces). Note on roof, desks, tank.",
    projectSlug: "likoni-ecd-classrooms",
    county: "Mombasa",
    rewardKes: 4_000,
    status: "paid",
    days: -20,
    subs: [
      {
        hunter: "seed-hunter-e",
        name: "Monitor 02",
        proof: "Building in use. Roof, desks, tank present. Eight visits already agree.",
        status: "accepted",
      },
    ],
  },
  {
    slug: "dadaab-pan-holds",
    posterName: "Water-user group · Dadaab",
    title: "Dadaab pan: water after rains, fence and trough",
    titleSw: "Dimba Dadaab: maji baada ya mvua, uzio na kiorosho",
    description: "Practical completion November 2023. Confirm the pan still holds.",
    deliverables: "Photograph of the basin. Fence yes/no. Trough yes/no.",
    projectSlug: "dadaab-water-pan",
    county: "Garissa",
    rewardKes: 3_500,
    status: "paid",
    days: -40,
    subs: [
      {
        hunter: "seed-hunter-f",
        name: "Monitor 08",
        proof: "Pan holds after rains. Fence and trough in place.",
        status: "accepted",
      },
    ],
  },
  {
    slug: "kaptembwo-shell",
    posterName: "Patient group (demo)",
    title: "Kaptembwo imaging wing: shell only, or equipment",
    titleSw: "Wingo ya picha Kaptembwo: gamba tu, au vifaa",
    description: "Contract extended three times. Need a current photograph of the shell and a note on equipment.",
    deliverables: "Photograph of the wing. Equipment yes/no. Roof sheets on/off.",
    projectSlug: "kaptembwo-imaging-wing",
    county: "Nakuru",
    rewardKes: 7_000,
    status: "closed",
    days: -5,
    subs: [
      {
        hunter: SEED_HUNTER,
        name: "Monitor 04",
        proof: "Shell standing since 2023. No equipment. Roof sheets partly on.",
        status: "rejected",
      },
    ],
  },
  {
    slug: "kakuma-noon-dusk",
    posterName: "Health watch · Turkana",
    title: "Film Kakuma staff-house plot at noon and after dusk",
    titleSw: "Piga picha kiwanja cha nyumba Kakuma adhuhuri na baada ya giza",
    description:
      "One visit is not enough. Need two timestamps on the same GPS point so a midday empty plot cannot be explained as 'contractor on lunch'.",
    deliverables: "Two photographs, same GPS, noon and after 19:00. No faces. Short note on foundations.",
    projectSlug: "kakuma-staff-houses",
    county: "Turkana",
    rewardKes: 25_000,
    status: "open",
    days: 22,
    subs: [],
  },
  {
    slug: "malindi-doors-friday",
    posterName: "School board clerk (demo)",
    title: "Malindi sanitation block: doors on or off before Friday",
    titleSw: "Vyoo Malindi: milango ipo au hapana kabla ya Ijumaa",
    description:
      "The next board sitting is Friday. Need a current count of doors, roof sheets, and whether the pit is lined.",
    deliverables: "Count of doors. Photograph of the roof. Note on pit lining. GPS at the school gate.",
    projectSlug: "malindi-sanitation-block",
    county: "Kilifi",
    rewardKes: 3_500,
    status: "open",
    days: 1,
    subs: [
      { hunter: "seed-hunter-c", name: "Monitor 19", proof: "Two door frames, no leaves. Roof sheets on. Pit unlined.", status: "pending" },
    ],
  },
  {
    slug: "kitui-scrape-depth",
    posterName: "Water user group · Kisasi",
    title: "Measure Kitui Zone 4 scrape against a walking stick",
    titleSw: "Pima kina cha bwawa Kitui Eneo 4 kwa fimbo",
    description:
      "Certificate paid. Need a photograph of a stick or tape in the basin so the scrape can be compared to a spillway later.",
    deliverables: "Photograph of the basin with a measured stick. Photograph of any spillway. GPS.",
    projectSlug: "kitui-earth-dam",
    county: "Kitui",
    rewardKes: 15_000,
    status: "open",
    days: 12,
    subs: [],
  },
  {
    slug: "kayole-lane-count",
    posterName: "Market lane committee",
    title: "Kayole Lot B: lamps that actually light the stall row",
    titleSw: "Kayole Kundi B: taa zinazowasha mstari wa maduka",
    description: "Poles on paper. Need which lamps throw light onto the stall row, not the road.",
    deliverables: "Count of poles, working lamps, dark lamps. Photograph of the stall row after dark. GPS at two ends.",
    projectSlug: "kayole-lighting-b",
    county: "Nairobi",
    rewardKes: 2_000,
    status: "open",
    days: 4,
    subs: [],
  },
  {
    slug: "likoni-tank-still-there",
    posterName: "Coast education desk",
    title: "Likoni ECD tank: still on the slab, or gone",
    titleSw: "Tanki la ECD Likoni: bado kwenye slab, au limeenda",
    description: "Building was verified in use. Need a current photograph of the tank and roof after the last rains.",
    deliverables: "Photograph of tank. Photograph of roof. Note: in the timetable yes/no. No children's faces.",
    projectSlug: "likoni-ecd-classrooms",
    county: "Mombasa",
    rewardKes: 4_200,
    status: "open",
    days: 8,
    subs: [],
  },
  {
    slug: "kinondoni-borehole-pad",
    posterName: "Ward water table · Kinondoni",
    title: "Kinondoni borehole Phase II: pad only, or pump and tank",
    titleSw: "Kisima Kinondoni Awamu II: slab tu, au pampu na tanki",
    description: "Final certificate paid. We need a current photograph of the slab.",
    deliverables: "Photograph of the pad. Note: pump yes/no, tank yes/no. GPS.",
    projectSlug: "kinondoni-borehole-ii",
    county: "Dar es Salaam",
    country: "tz",
    rewardKes: 8_000,
    status: "open",
    days: 18,
    subs: [],
  },
  {
    slug: "arusha-poles-after-dark",
    posterName: "Market lane committee · Sekei",
    title: "Count standing Arusha Lot B poles after dark",
    titleSw: "Hesabu nguzo za Arusha Kundi B baada ya giza",
    description: "Forty poles on paper. Count what is standing, what has a lamp, and which are dark on the market lane.",
    deliverables: "Count of poles, lamps, dark poles. One photograph of the market lane. GPS at two ends.",
    projectSlug: "arusha-street-lighting",
    county: "Arusha",
    country: "tz",
    rewardKes: 4_500,
    status: "open",
    days: 9,
    subs: [],
  },
  {
    slug: "ilala-drain-cover",
    posterName: "Traders' welfare · Ilala",
    title: "Ilala Lot C: cover slabs on the market drain, or open trench",
    titleSw: "Ilala Kundi C: slabs za mfereji, au mtaro wazi",
    description: "Works certified complete. Need a walk of the market lane after a short rain.",
    deliverables: "Photograph of the lane. Cover slabs yes/no. GPS at two ends.",
    projectSlug: "ilala-drainage-lot-c",
    county: "Dar es Salaam",
    country: "tz",
    rewardKes: 7_000,
    status: "open",
    days: 14,
    subs: [],
  },
  {
    slug: "kawempe-pad-only",
    posterName: "Ward water table · Kawempe",
    title: "Kawempe borehole Phase II: pad only, or pump and tank",
    titleSw: "Kisima Kawempe Awamu II: slab tu, au pampu na tanki",
    description: "Final certificate paid. We need a current photograph of the slab.",
    deliverables: "Photograph of the pad. Note: pump yes/no, tank yes/no. GPS.",
    projectSlug: "kawempe-borehole-ii",
    county: "Kampala",
    country: "ug",
    rewardKes: 8_000,
    status: "open",
    days: 16,
    subs: [],
  },
  {
    slug: "ablekuma-empty-pad",
    posterName: "Water watch · Ablekuma",
    title: "Ablekuma borehole: empty pad or working pump",
    titleSw: "Ablekuma borehole: empty pad or working pump",
    description: "Paper says the borehole is complete. Walk the plot. Show the pad, the pump, or the empty ground.",
    deliverables: "Photograph of the pad. GPS. Note: pump yes/no.",
    projectSlug: "ablekuma-borehole",
    county: "Greater Accra",
    country: "gh",
    rewardKes: 6_000,
    status: "open",
    days: 14,
    subs: [],
  },
  {
    slug: "pikine-forage-pad",
    posterName: "Comité d'eau · Pikine",
    title: "Pikine forage: dalle seulement, ou pompe",
    titleSw: "Forage de Pikine : dalle seulement, ou pompe",
    description: "Le certificat final est payé. Il faut une photo actuelle de la dalle.",
    deliverables: "Photo de la dalle. GPS. Pompe oui/non.",
    projectSlug: "pikine-forage",
    county: "Dakar",
    country: "sn",
    rewardKes: 250_000,
    status: "open",
    days: 14,
    subs: [],
  },
  {
    slug: "agoe-forage-pad",
    posterName: "Comité local · Agoè",
    title: "Agoè forage: dalle ou pompe",
    titleSw: "Forage d'Agoè : dalle ou pompe",
    description: "Le papier dit terminé. Filmer la dalle. Pas de visages.",
    deliverables: "Photo de la dalle. GPS. Pompe oui/non.",
    projectSlug: "agoe-forage",
    county: "Maritime",
    country: "tg",
    rewardKes: 180_000,
    status: "open",
    days: 12,
    subs: [],
  },
  {
    slug: "kanyama-borehole-pad",
    posterName: "Water user group · Kanyama",
    title: "Kanyama borehole: pad only, or pump",
    titleSw: "Kanyama borehole: pad only, or pump",
    description: "Final certificate paid. Photograph the slab. Note pump and tank.",
    deliverables: "Photograph of the pad. GPS. Pump yes/no.",
    projectSlug: "kanyama-borehole",
    county: "Lusaka",
    country: "zm",
    rewardKes: 4_000,
    status: "open",
    days: 14,
    subs: [],
  },
  {
    slug: "lilongwe-borehole-pad",
    posterName: "Ward water table · Lilongwe",
    title: "Lilongwe borehole: pad only, or pump and tank",
    titleSw: "Lilongwe borehole: pad only, or pump and tank",
    description: "Final certificate paid. We need a current photograph of the slab.",
    deliverables: "Photograph of the pad. GPS. Pump yes/no.",
    projectSlug: "lilongwe-borehole",
    county: "Lilongwe",
    country: "mw",
    rewardKes: 250_000,
    status: "open",
    days: 14,
    subs: [],
  },
];

export { SEED_POSTER };
