import type { CountryId } from "./country";
import type { NextStep, Project } from "./types";

type Spec = {
  slug: string;
  country: CountryId;
  name: string;
  nameAlt: string;
  county: string;
  ward: string;
  sector: Project["sector"];
  status: Project["status"];
  fy: string;
  allocated: number;
  disbursed: number;
  contractor: string;
  promised: string;
  promisedAlt: string;
  paper: string;
  paperAlt: string;
  ground: string;
  groundAlt: string;
  lat: number;
  lng: number;
  photo: string;
  lastOfficial: string;
  seedReports: number;
  bountyKes: number;
  dept: string;
  deptAlt: string;
  auditor: string;
  auditorUrl: string;
  ati: NextStep;
  graft: NextStep;
  local: NextStep;
};

function offices(
  region: string,
  ward: string,
  dept: string,
  deptAlt: string,
  regionWord: string,
): Project["responsible"] {
  return [
    {
      office: `Ward office, ${ward}`,
      officeSw: `Ofisi ya kata, ${ward}`,
      duty: "Tables this project locally. Asks why payment ran ahead of the work on the ground.",
      dutySw: "Wasilisha mradi huu. Uliza kwa nini malipo yalikimbia mbele ya kazi ardhini.",
    },
    {
      office: `${region} ${regionWord}, ${dept}`,
      officeSw: `${region}, ${deptAlt}`,
      duty: "The procuring entity. Holds the contract, payment certificates, and GPS.",
      dutySw: "Shirika lililonunua. Linashikilia mkataba, vyeti vya malipo, na GPS.",
    },
  ];
}

function row(s: Spec): Project {
  return {
    slug: s.slug,
    name: s.name,
    nameSw: s.nameAlt,
    county: s.county,
    ward: s.ward,
    sector: s.sector,
    status: s.status,
    fy: s.fy,
    allocatedKes: s.allocated,
    disbursedKes: s.disbursed,
    contractor: s.contractor,
    promised: s.promised,
    promisedSw: s.promisedAlt,
    paperClaim: s.paper,
    paperClaimSw: s.paperAlt,
    groundNote: s.ground,
    groundNoteSw: s.groundAlt,
    lat: s.lat,
    lng: s.lng,
    photo: s.photo,
    lastOfficial: s.lastOfficial,
    sources: [
      {
        name: s.auditor,
        url: s.auditorUrl,
        published: "2025",
        what: "Demo patterned on published audit problems in this country. Not a live extract.",
      },
    ],
    nextSteps: [s.graft, s.ati, s.local],
    seedReports: s.seedReports,
    bountyKes: s.bountyKes,
    responsible: offices(s.county, s.ward, s.dept, s.deptAlt, "administration"),
    country: s.country,
  };
}

const ugOag: NextStep = {
  office: "Office of the Auditor General (Uganda)",
  action: "Ask the Auditor General to include this site in the next district audit. Attach the observation hash.",
  actionSw: "Omba Mkaguzi Mkuu aingize eneo hili katika ukaguzi ujao wa wilaya. Ambatanisha hash.",
  contact: "oag.go.ug",
  url: "https://www.oag.go.ug/",
  needs: ["Project name and ward", "FY and allocated amount", "Observation hash", "GPS"],
};
const ugIgg: NextStep = {
  office: "Inspectorate of Government",
  action: "File a report if public funds were paid for work that was not done. Stick to what you saw.",
  actionSw: "Wasilisha ripoti ikiwa pesa za umma zililipwa kwa kazi isiyofanyika. Shika ulichoona.",
  contact: "igg.go.ug",
  url: "https://www.igg.go.ug/",
  needs: ["What was paid for", "What is on the ground", "Dates you visited"],
};
const ugAti: NextStep = {
  office: "Access to Information Act, 2005",
  action: "Request the contract, bills of quantities, and payment certificates from the accounting officer. The clock is 21 days.",
  actionSw: "Omba mkataba, bili za kiasi, na vyeti vya malipo. Saa ni siku 21.",
  contact: "Accounting officer of the district or ministry",
  url: "https://www.oag.go.ug/",
  needs: ["Your postal or email address", "Exact document titles", "21 days"],
};
const ugLocal: NextStep = {
  office: "District / LC5 / councillor",
  action: "Table the ledger row. Ask why disbursement ran ahead of the slab or the pump.",
  actionSw: "Wasilisha mstari. Uliza kwa nini malipo yalikimbia mbele ya slab au pampu.",
  contact: "District headquarters",
  url: "https://www.gou.go.ug/",
  needs: ["Print the project page or copy the hash"],
};

const ghAs: NextStep = {
  office: "Ghana Audit Service",
  action: "Ask the Auditor-General to include this site in the next MDA or MMDAs audit. Attach the hash.",
  actionSw: "Ask the Auditor-General to include this site in the next audit. Attach the hash.",
  contact: "ghaudit.org",
  url: "https://ghaudit.org/",
  needs: ["Project name", "FY", "Observation hash", "GPS"],
};
const ghChraj: NextStep = {
  office: "CHRAJ / Office of the Special Prosecutor",
  action: "Use this when money appears to have been paid for work that was not done.",
  actionSw: "Use this when money appears to have been paid for work that was not done.",
  contact: "chraj.gov.gh",
  url: "https://chraj.gov.gh/",
  needs: ["What was paid for", "What is on the ground", "Dates you visited"],
};
const ghAti: NextStep = {
  office: "Right to Information Act, 2019 (Act 989)",
  action: "Request the contract, BoQ, and payment certificates. The clock is 14 days, extendable by 14.",
  actionSw: "Request the contract, BoQ, and payment certificates. The clock is 14 days.",
  contact: "Information officer of the procuring entity",
  url: "https://rti.gov.gh/",
  needs: ["Your address", "Exact titles", "14 days"],
};
const ghLocal: NextStep = {
  office: "Assembly member / MMDA",
  action: "Table the ledger row at the assembly. Ask why payment ran ahead of the work.",
  actionSw: "Table the ledger row at the assembly.",
  contact: "Metropolitan / Municipal / District Assembly",
  url: "https://www.mlgrd.gov.gh/",
  needs: ["Print the project page or copy the hash"],
};

const snCdc: NextStep = {
  office: "Cour des comptes",
  action: "Demandez que le site entre dans le prochain contrôle. Joignez le hash d’observation.",
  actionSw: "Demandez que le site entre dans le prochain contrôle. Joignez le hash d’observation.",
  contact: "coursdescomptes.sn",
  url: "https://www.coursdescomptes.sn/",
  needs: ["Nom du projet", "Exercice", "Hash", "GPS"],
};
const snOfnac: NextStep = {
  office: "OFNAC",
  action: "Signalez un paiement pour un ouvrage introuvable. Tenez-vous à ce que vous avez vu.",
  actionSw: "Signalez un paiement pour un ouvrage introuvable. Tenez-vous à ce que vous avez vu.",
  contact: "ofnac.sn",
  url: "https://www.ofnac.sn/",
  needs: ["Objet payé", "Ce qui est au sol", "Dates de visite"],
};
const snAti: NextStep = {
  office: "Cour des comptes / OFNAC",
  action: "Demandez le marché, le bordereau des prix, et les décomptes au comptable assignataire.",
  actionSw: "Demandez le marché, le bordereau des prix, et les décomptes au comptable assignataire.",
  contact: "Comptable de la collectivité ou du ministère",
  url: "https://www.coursdescomptes.sn/",
  needs: ["Adresse", "Titres exacts", "30 jours"],
};
const snLocal: NextStep = {
  office: "Maire / conseil municipal",
  action: "Portez la ligne au conseil. Demandez pourquoi le paiement a précédé le chantier.",
  actionSw: "Portez la ligne au conseil. Demandez pourquoi le paiement a précédé le chantier.",
  contact: "Hôtel de ville",
  url: "https://www.sec.gouv.sn/",
  needs: ["Imprimer la page ou copier le hash"],
};

const tgCdc: NextStep = {
  office: "Cour des comptes du Togo",
  action: "Demandez que le site entre dans le prochain contrôle. Joignez le hash.",
  actionSw: "Demandez que le site entre dans le prochain contrôle. Joignez le hash.",
  contact: "courdescomptes.tg",
  url: "https://courdescomptes.tg/",
  needs: ["Nom du projet", "Exercice", "Hash", "GPS"],
};
const tgHap: NextStep = {
  office: "HAPLUCIA",
  action: "Signalez un paiement pour un ouvrage introuvable. Tenez-vous à ce que vous avez vu.",
  actionSw: "Signalez un paiement pour un ouvrage introuvable.",
  contact: "haplucia.tg",
  url: "https://haplucia.tg/",
  needs: ["Objet payé", "Ce qui est au sol", "Dates de visite"],
};
const tgAti: NextStep = {
  office: "Pétition Cour des comptes / HAPLUCIA",
  action: "Demandez le marché, le bordereau, et les décomptes au comptable assignataire.",
  actionSw: "Demandez le marché, le bordereau, et les décomptes.",
  contact: "Comptable de la préfecture ou du ministère",
  url: "https://courdescomptes.tg/",
  needs: ["Adresse", "Titres exacts"],
};
const tgLocal: NextStep = {
  office: "Maire / conseil",
  action: "Portez la ligne au conseil. Demandez pourquoi le paiement a précédé le chantier.",
  actionSw: "Portez la ligne au conseil.",
  contact: "Mairie",
  url: "https://www.republiquetogolaise.com/",
  needs: ["Imprimer la page ou copier le hash"],
};

const zmAgo: NextStep = {
  office: "Office of the Auditor General (Zambia)",
  action: "Ask the Auditor-General to include this site in the next provincial audit. Attach the hash.",
  actionSw: "Ask the Auditor-General to include this site in the next audit. Attach the hash.",
  contact: "ago.gov.zm",
  url: "https://www.ago.gov.zm/",
  needs: ["Project name", "FY", "Observation hash", "GPS"],
};
const zmAcc: NextStep = {
  office: "Anti-Corruption Commission",
  action: "File a report if public funds were paid for work that was not done.",
  actionSw: "File a report if public funds were paid for work that was not done.",
  contact: "acc.gov.zm",
  url: "https://www.acc.gov.zm/",
  needs: ["What was paid for", "What is on the ground", "Dates you visited"],
};
const zmAti: NextStep = {
  office: "Access to Information Act, 2013",
  action: "Request the contract, BoQ, and payment certificates. The clock is 30 days.",
  actionSw: "Request the contract, BoQ, and payment certificates. The clock is 30 days.",
  contact: "Information officer of the procuring entity",
  url: "https://www.ago.gov.zm/",
  needs: ["Your address", "Exact titles", "30 days"],
};
const zmLocal: NextStep = {
  office: "Councillor / local authority",
  action: "Table the ledger row. Ask why payment ran ahead of the work.",
  actionSw: "Table the ledger row.",
  contact: "Civic centre",
  url: "https://www.mlgrd.gov.zm/",
  needs: ["Print the project page or copy the hash"],
};

const mwNao: NextStep = {
  office: "National Audit Office (Malawi)",
  action: "Ask NAO to include this site in the next council audit. Attach the hash.",
  actionSw: "Ask NAO to include this site in the next council audit. Attach the hash.",
  contact: "nao.gov.mw",
  url: "https://www.nao.gov.mw/",
  needs: ["Project name", "FY", "Observation hash", "GPS"],
};
const mwAcb: NextStep = {
  office: "Anti-Corruption Bureau",
  action: "File a report if public funds were paid for work that was not done.",
  actionSw: "File a report if public funds were paid for work that was not done.",
  contact: "acbmw.org",
  url: "https://www.acbmw.org/",
  needs: ["What was paid for", "What is on the ground", "Dates you visited"],
};
const mwAti: NextStep = {
  office: "Access to Information Act, 2017",
  action: "Request the contract, BoQ, and payment certificates. The clock is 30 days.",
  actionSw: "Request the contract, BoQ, and payment certificates.",
  contact: "Information officer of the council or ministry",
  url: "https://www.nao.gov.mw/",
  needs: ["Your address", "Exact titles", "30 days"],
};
const mwLocal: NextStep = {
  office: "Councillor / district council",
  action: "Table the ledger row. Ask why payment ran ahead of the work.",
  actionSw: "Table the ledger row.",
  contact: "District commissioner",
  url: "https://www.malawi.gov.mw/",
  needs: ["Print the project page or copy the hash"],
};

export const PILOT_PROJECTS: Project[] = [
  row({
    slug: "kawempe-borehole-ii",
    country: "ug",
    name: "Kawempe Ward Community Borehole, Phase II",
    nameAlt: "Kisima cha Jamii, Kata ya Kawempe, Awamu ya II",
    county: "Kampala",
    ward: "Kawempe",
    sector: "water",
    status: "ghost",
    fy: "2023/24",
    allocated: 48_000_000,
    disbursed: 48_000_000,
    contractor: "Hill Drill Works (demo name)",
    promised: "A 120-metre borehole, solar pump, 10,000-litre tank, two tap stands.",
    promisedAlt: "Kisima cha mita 120, pampu ya sola, tanki la lita 10,000, vituo viwili.",
    paper: "Final certificate paid. Marked complete in the district file.",
    paperAlt: "Cheti cha mwisho kililipwa. Imeandikwa imekamilika.",
    ground: "Concrete pad only. No casing, no pump, no tank.",
    groundAlt: "Slab ya zege tu. Hakuna bomba, pampu, wala tanki.",
    lat: 0.363,
    lng: 32.561,
    photo: "/evidence/borehole.jpg",
    lastOfficial: "2025-11-02",
    seedReports: 8,
    bountyKes: 8_000,
    dept: "Water",
    deptAlt: "Maji",
    auditor: "Office of the Auditor General (Uganda)",
    auditorUrl: "https://www.oag.go.ug/",
    ati: ugAti,
    graft: ugIgg,
    local: ugLocal,
  }),
  row({
    slug: "gulu-classroom-block",
    country: "ug",
    name: "Pece ECD Twin Classroom",
    nameAlt: "Madarasa Mapacha ya ECD, Pece",
    county: "Gulu",
    ward: "Pece",
    sector: "education",
    status: "incomplete",
    fy: "2022/23",
    allocated: 92_000_000,
    disbursed: 71_000_000,
    contractor: "North Build (demo name)",
    promised: "Two classrooms, office, latrine, and a rain tank.",
    promisedAlt: "Madarasa mawili, ofisi, choo, na tanki la mvua.",
    paper: "75% paid. Marked substantially complete.",
    paperAlt: "75% imelipwa. Imeandikwa imekaribia kukamilika.",
    ground: "Walls to window height. No roof. Grass through the slab.",
    groundAlt: "Kuta hadi dirisha. Hakuna paa. Nyasi kwenye slab.",
    lat: 2.774,
    lng: 32.299,
    photo: "/evidence/classroom.jpg",
    lastOfficial: "2025-08-14",
    seedReports: 6,
    bountyKes: 6_000,
    dept: "Education",
    deptAlt: "Elimu",
    auditor: "Office of the Auditor General (Uganda)",
    auditorUrl: "https://www.oag.go.ug/",
    ati: ugAti,
    graft: ugIgg,
    local: ugLocal,
  }),
  row({
    slug: "mbale-dispensary-wing",
    country: "ug",
    name: "Namakwekwe Dispensary Extension",
    nameAlt: "Kiambatisho cha Zahanati, Namakwekwe",
    county: "Mbale",
    ward: "Namakwekwe",
    sector: "health",
    status: "delayed",
    fy: "2023/24",
    allocated: 140_000_000,
    disbursed: 55_000_000,
    contractor: "Elgon Health Works (demo name)",
    promised: "Maternity wing, placenta pit, and a solar fridge line.",
    promisedAlt: "Wodi ya uzazi, shimo la kondo, na mstari wa friji ya sola.",
    paper: "First certificate paid. Completion still inside the contract clock.",
    paperAlt: "Cheti cha kwanza kililipwa. Bado ndani ya saa ya mkataba.",
    ground: "Foundation and columns. No walls. No fridge.",
    groundAlt: "Msingi na nguzo. Hakuna kuta. Hakuna friji.",
    lat: 1.078,
    lng: 34.181,
    photo: "/evidence/dispensary.jpg",
    lastOfficial: "2025-10-03",
    seedReports: 4,
    bountyKes: 5_000,
    dept: "Health",
    deptAlt: "Afya",
    auditor: "Office of the Auditor General (Uganda)",
    auditorUrl: "https://www.oag.go.ug/",
    ati: ugAti,
    graft: ugIgg,
    local: ugLocal,
  }),
  row({
    slug: "ablekuma-borehole",
    country: "gh",
    name: "Ablekuma Community Borehole, Lot B",
    nameAlt: "Ablekuma Community Borehole, Lot B",
    county: "Greater Accra",
    ward: "Ablekuma",
    sector: "water",
    status: "ghost",
    fy: "2023/24",
    allocated: 185_000,
    disbursed: 185_000,
    contractor: "Coast Drill Ghana (demo name)",
    promised: "A drilled borehole, solar pump, elevated tank, two standpipes.",
    promisedAlt: "A drilled borehole, solar pump, elevated tank, two standpipes.",
    paper: "Final certificate paid. Marked complete in the assembly file.",
    paperAlt: "Final certificate paid. Marked complete in the assembly file.",
    ground: "Concrete pad only. No pump, no tank. Neighbours still buy from vendors.",
    groundAlt: "Concrete pad only. No pump, no tank.",
    lat: 5.56,
    lng: -0.27,
    photo: "/evidence/borehole.jpg",
    lastOfficial: "2025-09-18",
    seedReports: 7,
    bountyKes: 800,
    dept: "Works",
    deptAlt: "Works",
    auditor: "Ghana Audit Service",
    auditorUrl: "https://ghaudit.org/",
    ati: ghAti,
    graft: ghChraj,
    local: ghLocal,
  }),
  row({
    slug: "kumasi-streetlights",
    country: "gh",
    name: "Asawase Street Lighting Lot C",
    nameAlt: "Asawase Street Lighting Lot C",
    county: "Ashanti",
    ward: "Asawase",
    sector: "energy",
    status: "incomplete",
    fy: "2022/23",
    allocated: 420_000,
    disbursed: 310_000,
    contractor: "Ashanti Poles (demo name)",
    promised: "Forty solar street lights on the market stretch.",
    promisedAlt: "Forty solar street lights on the market stretch.",
    paper: "Paid to 74%. Marked substantially complete.",
    paperAlt: "Paid to 74%. Marked substantially complete.",
    ground: "Twelve poles standing. Eight have no panel. The rest are a stacking yard.",
    groundAlt: "Twelve poles standing. Eight have no panel.",
    lat: 6.688,
    lng: -1.624,
    photo: "/evidence/streetlights.jpg",
    lastOfficial: "2025-07-11",
    seedReports: 5,
    bountyKes: 600,
    dept: "Works",
    deptAlt: "Works",
    auditor: "Ghana Audit Service",
    auditorUrl: "https://ghaudit.org/",
    ati: ghAti,
    graft: ghChraj,
    local: ghLocal,
  }),
  row({
    slug: "tamale-clinic-wing",
    country: "gh",
    name: "Changli CHPS Compound Extension",
    nameAlt: "Changli CHPS Compound Extension",
    county: "Northern",
    ward: "Changli",
    sector: "health",
    status: "ghost",
    fy: "2023/24",
    allocated: 640_000,
    disbursed: 640_000,
    contractor: "Savannah Health Build (demo name)",
    promised: "Delivery room, placenta pit, and a solar fridge line.",
    promisedAlt: "Delivery room, placenta pit, and a solar fridge line.",
    paper: "Final certificate paid.",
    paperAlt: "Final certificate paid.",
    ground: "Empty plot. Survey pegs in the grass. No slab.",
    groundAlt: "Empty plot. Survey pegs in the grass. No slab.",
    lat: 9.401,
    lng: -0.839,
    photo: "/evidence/empty-plot.jpg",
    lastOfficial: "2025-06-02",
    seedReports: 9,
    bountyKes: 900,
    dept: "Health",
    deptAlt: "Health",
    auditor: "Ghana Audit Service",
    auditorUrl: "https://ghaudit.org/",
    ati: ghAti,
    graft: ghChraj,
    local: ghLocal,
  }),
  row({
    slug: "pikine-forage",
    country: "sn",
    name: "Pikine community borehole, phase II",
    nameAlt: "Forage communautaire de Pikine, phase II",
    county: "Dakar",
    ward: "Pikine",
    sector: "water",
    status: "ghost",
    fy: "2023/24",
    allocated: 28_000_000,
    disbursed: 28_000_000,
    contractor: "Sahel Forage (nom démo)",
    promised: "A 120-metre borehole, solar pump, 10,000-litre tank, two taps.",
    promisedAlt: "Forage de 120 mètres, pompe solaire, château de 10 000 litres, deux bornes.",
    paper: "Décompte final payé. Marqué achevé au dossier de la collectivité.",
    paperAlt: "Décompte final payé. Marqué achevé au dossier de la collectivité.",
    ground: "Dalle seule. Pas de pompe, pas de château. Les voisins achètent encore aux citernes.",
    groundAlt: "Dalle seule. Pas de pompe, pas de château. Les voisins achètent encore aux citernes.",
    lat: 14.765,
    lng: -17.391,
    photo: "/evidence/borehole.jpg",
    lastOfficial: "2025-10-21",
    seedReports: 6,
    bountyKes: 8_000,
    dept: "Hydraulique",
    deptAlt: "Hydraulique",
    auditor: "Cour des comptes du Sénégal",
    auditorUrl: "https://www.coursdescomptes.sn/",
    ati: snAti,
    graft: snOfnac,
    local: snLocal,
  }),
  row({
    slug: "thies-marche",
    country: "sn",
    name: "Thiès market shade, lot C",
    nameAlt: "Ombrières du marché de Thiès, lot C",
    county: "Thiès",
    ward: "Thiès Nord",
    sector: "housing",
    status: "incomplete",
    fy: "2022/23",
    allocated: 95_000_000,
    disbursed: 70_000_000,
    contractor: "Cap-Vert Structures (nom démo)",
    promised: "Forty stall shades, drainage, and two latrine blocks.",
    promisedAlt: "Quarante ombrières, drainage, et deux blocs de latrines.",
    paper: "Payé à 74 %. Marqué substantiellement achevé.",
    paperAlt: "Payé à 74 %. Marqué substantiellement achevé.",
    ground: "Twelve poles. No roof sheets. Drainage is a trench.",
    groundAlt: "Douze poteaux. Pas de tôles. Le drainage est une tranchée.",
    lat: 14.79,
    lng: -16.926,
    photo: "/evidence/market.jpg",
    lastOfficial: "2025-08-09",
    seedReports: 4,
    bountyKes: 6_000,
    dept: "Urbanisme",
    deptAlt: "Urbanisme",
    auditor: "Cour des comptes du Sénégal",
    auditorUrl: "https://www.coursdescomptes.sn/",
    ati: snAti,
    graft: snOfnac,
    local: snLocal,
  }),
  row({
    slug: "saintlouis-latrine",
    country: "sn",
    name: "Sor primary sanitation block",
    nameAlt: "Bloc sanitaire de l'école de Sor",
    county: "Saint-Louis",
    ward: "Sor",
    sector: "education",
    status: "ghost",
    fy: "2023/24",
    allocated: 18_500_000,
    disbursed: 18_500_000,
    contractor: "Fleuve Bâtiment (nom démo)",
    promised: "Four-cabin latrine, hand-wash, and a soak pit.",
    promisedAlt: "Latrines de quatre cabines, lave-mains, et puisard.",
    paper: "Décompte final payé.",
    paperAlt: "Décompte final payé.",
    ground: "Empty plot behind the classrooms. Survey pegs in the grass.",
    groundAlt: "Parcelle vide derrière les classes. Piquets dans l'herbe.",
    lat: 16.028,
    lng: -16.49,
    photo: "/evidence/latrine.jpg",
    lastOfficial: "2025-05-30",
    seedReports: 5,
    bountyKes: 5_000,
    dept: "Éducation",
    deptAlt: "Éducation",
    auditor: "Cour des comptes du Sénégal",
    auditorUrl: "https://www.coursdescomptes.sn/",
    ati: snAti,
    graft: snOfnac,
    local: snLocal,
  }),
  row({
    slug: "agoe-forage",
    country: "tg",
    name: "Agoè community borehole",
    nameAlt: "Forage communautaire d'Agoè",
    county: "Lomé",
    ward: "Agoè-Nyivé",
    sector: "water",
    status: "ghost",
    fy: "2023/24",
    allocated: 22_000_000,
    disbursed: 22_000_000,
    contractor: "Golfe Forage (nom démo)",
    promised: "A drilled borehole, solar pump, elevated tank, two taps.",
    promisedAlt: "Forage, pompe solaire, château, deux bornes.",
    paper: "Décompte final payé. Marqué achevé.",
    paperAlt: "Décompte final payé. Marqué achevé.",
    ground: "Dalle seule. Pas de pompe. Les voisins achètent encore aux citernes.",
    groundAlt: "Dalle seule. Pas de pompe. Les voisins achètent encore aux citernes.",
    lat: 6.237,
    lng: 1.203,
    photo: "/evidence/borehole.jpg",
    lastOfficial: "2025-09-04",
    seedReports: 6,
    bountyKes: 7_000,
    dept: "Hydraulique",
    deptAlt: "Hydraulique",
    auditor: "Cour des comptes du Togo",
    auditorUrl: "https://courdescomptes.tg/",
    ati: tgAti,
    graft: tgHap,
    local: tgLocal,
  }),
  row({
    slug: "kara-ecole",
    country: "tg",
    name: "Kara ECD twin classroom",
    nameAlt: "Salles jumelles préscolaires, Kara",
    county: "Kara",
    ward: "Kara",
    sector: "education",
    status: "incomplete",
    fy: "2022/23",
    allocated: 48_000_000,
    disbursed: 31_000_000,
    contractor: "Kozah Bâtiment (nom démo)",
    promised: "Two classrooms, office, and a latrine block.",
    promisedAlt: "Deux salles, un bureau, et un bloc de latrines.",
    paper: "Payé à 65 %. Marqué substantiellement achevé.",
    paperAlt: "Payé à 65 %. Marqué substantiellement achevé.",
    ground: "Walls to window height. No roof.",
    groundAlt: "Murs à hauteur des fenêtres. Pas de toiture.",
    lat: 9.551,
    lng: 1.186,
    photo: "/evidence/classroom.jpg",
    lastOfficial: "2025-07-22",
    seedReports: 3,
    bountyKes: 5_000,
    dept: "Éducation",
    deptAlt: "Éducation",
    auditor: "Cour des comptes du Togo",
    auditorUrl: "https://courdescomptes.tg/",
    ati: tgAti,
    graft: tgHap,
    local: tgLocal,
  }),
  row({
    slug: "sokode-marche",
    country: "tg",
    name: "Sokodé market drainage, lot A",
    nameAlt: "Drainage du marché de Sokodé, lot A",
    county: "Centrale",
    ward: "Sokodé",
    sector: "roads",
    status: "delayed",
    fy: "2023/24",
    allocated: 36_000_000,
    disbursed: 12_000_000,
    contractor: "Tchaoudjo VRD (nom démo)",
    promised: "Covered drain along the market edge and two crossings.",
    promisedAlt: "Caniveau couvert en bordure du marché et deux traversées.",
    paper: "First certificate paid. Still inside the contract clock.",
    paperAlt: "Premier décompte payé. Encore dans le délai du marché.",
    ground: "A trench. No cover slabs. Market waste in the cut.",
    groundAlt: "Une tranchée. Pas de dalles. Déchets du marché dans la fouille.",
    lat: 8.983,
    lng: 1.133,
    photo: "/evidence/road.jpg",
    lastOfficial: "2025-11-01",
    seedReports: 4,
    bountyKes: 4_000,
    dept: "Travaux",
    deptAlt: "Travaux",
    auditor: "Cour des comptes du Togo",
    auditorUrl: "https://courdescomptes.tg/",
    ati: tgAti,
    graft: tgHap,
    local: tgLocal,
  }),
  row({
    slug: "kanyama-borehole",
    country: "zm",
    name: "Kanyama community borehole, phase II",
    nameAlt: "Kanyama community borehole, phase II",
    county: "Lusaka",
    ward: "Kanyama",
    sector: "water",
    status: "ghost",
    fy: "2023/24",
    allocated: 280_000,
    disbursed: 280_000,
    contractor: "Kafue Drill (demo name)",
    promised: "A drilled borehole, solar pump, elevated tank, two taps.",
    promisedAlt: "A drilled borehole, solar pump, elevated tank, two taps.",
    paper: "Final certificate paid. Marked complete.",
    paperAlt: "Final certificate paid. Marked complete.",
    ground: "Concrete pad only. No pump, no tank.",
    groundAlt: "Concrete pad only. No pump, no tank.",
    lat: -15.432,
    lng: 28.248,
    photo: "/evidence/borehole.jpg",
    lastOfficial: "2025-08-19",
    seedReports: 7,
    bountyKes: 800,
    dept: "Water",
    deptAlt: "Water",
    auditor: "Office of the Auditor General (Zambia)",
    auditorUrl: "https://www.ago.gov.zm/",
    ati: zmAti,
    graft: zmAcc,
    local: zmLocal,
  }),
  row({
    slug: "ndola-clinic",
    country: "zm",
    name: "Twapia clinic extension",
    nameAlt: "Twapia clinic extension",
    county: "Copperbelt",
    ward: "Twapia",
    sector: "health",
    status: "incomplete",
    fy: "2022/23",
    allocated: 1_150_000,
    disbursed: 720_000,
    contractor: "Copper Health Build (demo name)",
    promised: "Maternity room, placenta pit, solar fridge.",
    promisedAlt: "Maternity room, placenta pit, solar fridge.",
    paper: "Paid to 63%. Marked substantially complete.",
    paperAlt: "Paid to 63%. Marked substantially complete.",
    ground: "Walls to window height. No roof. No fridge.",
    groundAlt: "Walls to window height. No roof. No fridge.",
    lat: -12.969,
    lng: 28.637,
    photo: "/evidence/clinic.jpg",
    lastOfficial: "2025-06-28",
    seedReports: 5,
    bountyKes: 700,
    dept: "Health",
    deptAlt: "Health",
    auditor: "Office of the Auditor General (Zambia)",
    auditorUrl: "https://www.ago.gov.zm/",
    ati: zmAti,
    graft: zmAcc,
    local: zmLocal,
  }),
  row({
    slug: "chipata-feeder",
    country: "zm",
    name: "Chipata feeder road 3.1 km",
    nameAlt: "Chipata feeder road 3.1 km",
    county: "Eastern",
    ward: "Chipata",
    sector: "roads",
    status: "ghost",
    fy: "2023/24",
    allocated: 2_400_000,
    disbursed: 2_400_000,
    contractor: "Luangwa Grade (demo name)",
    promised: "3.1 km gravel, two drifts, culvert rings.",
    promisedAlt: "3.1 km gravel, two drifts, culvert rings.",
    paper: "Final certificate paid for the full alignment.",
    paperAlt: "Final certificate paid for the full alignment.",
    ground: "Grade ends at 600 m. Culvert rings in the grass.",
    groundAlt: "Grade ends at 600 m. Culvert rings in the grass.",
    lat: -13.633,
    lng: 32.646,
    photo: "/evidence/road.jpg",
    lastOfficial: "2025-09-12",
    seedReports: 8,
    bountyKes: 900,
    dept: "Works",
    deptAlt: "Works",
    auditor: "Office of the Auditor General (Zambia)",
    auditorUrl: "https://www.ago.gov.zm/",
    ati: zmAti,
    graft: zmAcc,
    local: zmLocal,
  }),
  row({
    slug: "lilongwe-borehole",
    country: "mw",
    name: "Area 25 community borehole",
    nameAlt: "Area 25 community borehole",
    county: "Lilongwe",
    ward: "Area 25",
    sector: "water",
    status: "ghost",
    fy: "2023/24",
    allocated: 18_500_000,
    disbursed: 18_500_000,
    contractor: "Central Drill (demo name)",
    promised: "A drilled borehole, solar pump, tank, two taps.",
    promisedAlt: "A drilled borehole, solar pump, tank, two taps.",
    paper: "Final certificate paid. Marked complete.",
    paperAlt: "Final certificate paid. Marked complete.",
    ground: "Concrete pad only. No pump. Neighbours still queue at the kiosk.",
    groundAlt: "Concrete pad only. No pump.",
    lat: -13.983,
    lng: 33.787,
    photo: "/evidence/borehole.jpg",
    lastOfficial: "2025-10-08",
    seedReports: 9,
    bountyKes: 8_000,
    dept: "Water",
    deptAlt: "Water",
    auditor: "National Audit Office (Malawi)",
    auditorUrl: "https://www.nao.gov.mw/",
    ati: mwAti,
    graft: mwAcb,
    local: mwLocal,
  }),
  row({
    slug: "ndirande-classroom",
    country: "mw",
    name: "Ndirande ECD twin classroom",
    nameAlt: "Ndirande ECD twin classroom",
    county: "Blantyre",
    ward: "Ndirande",
    sector: "education",
    status: "incomplete",
    fy: "2022/23",
    allocated: 42_000_000,
    disbursed: 28_000_000,
    contractor: "Shire Build (demo name)",
    promised: "Two classrooms, office, latrine.",
    promisedAlt: "Two classrooms, office, latrine.",
    paper: "Paid to 67%. Marked substantially complete.",
    paperAlt: "Paid to 67%. Marked substantially complete.",
    ground: "Walls to window height. No roof. Grass through the slab.",
    groundAlt: "Walls to window height. No roof.",
    lat: -15.787,
    lng: 35.021,
    photo: "/evidence/classroom.jpg",
    lastOfficial: "2025-07-03",
    seedReports: 6,
    bountyKes: 6_000,
    dept: "Education",
    deptAlt: "Education",
    auditor: "National Audit Office (Malawi)",
    auditorUrl: "https://www.nao.gov.mw/",
    ati: mwAti,
    graft: mwAcb,
    local: mwLocal,
  }),
  row({
    slug: "mzuzu-clinic",
    country: "mw",
    name: "Mchengautuwa dispensary wing",
    nameAlt: "Mchengautuwa dispensary wing",
    county: "Mzimba",
    ward: "Mzuzu",
    sector: "health",
    status: "delayed",
    fy: "2023/24",
    allocated: 65_000_000,
    disbursed: 21_000_000,
    contractor: "North Health Works (demo name)",
    promised: "Delivery room, placenta pit, solar fridge.",
    promisedAlt: "Delivery room, placenta pit, solar fridge.",
    paper: "First certificate paid. Still inside the contract clock.",
    paperAlt: "First certificate paid.",
    ground: "Foundation and columns. No walls.",
    groundAlt: "Foundation and columns. No walls.",
    lat: -11.462,
    lng: 34.017,
    photo: "/evidence/clinic.jpg",
    lastOfficial: "2025-11-16",
    seedReports: 4,
    bountyKes: 5_000,
    dept: "Health",
    deptAlt: "Health",
    auditor: "National Audit Office (Malawi)",
    auditorUrl: "https://www.nao.gov.mw/",
    ati: mwAti,
    graft: mwAcb,
    local: mwLocal,
  }),
];

export const PILOT_REGIONS: Record<Exclude<CountryId, "ke" | "tz">, string[]> = {
  ug: [...new Set(PILOT_PROJECTS.filter((p) => p.country === "ug").map((p) => p.county))].sort(),
  gh: [...new Set(PILOT_PROJECTS.filter((p) => p.country === "gh").map((p) => p.county))].sort(),
  sn: [...new Set(PILOT_PROJECTS.filter((p) => p.country === "sn").map((p) => p.county))].sort(),
  tg: [...new Set(PILOT_PROJECTS.filter((p) => p.country === "tg").map((p) => p.county))].sort(),
  zm: [...new Set(PILOT_PROJECTS.filter((p) => p.country === "zm").map((p) => p.county))].sort(),
  mw: [...new Set(PILOT_PROJECTS.filter((p) => p.country === "mw").map((p) => p.county))].sort(),
};
