import type { NextStep, Project } from "./types";

const CAG = "https://www.nao.go.tz/";
const PCCB = "https://www.pccb.go.tz/";
const PPRA = "https://www.ppra.go.tz/";
const MOF = "https://www.mof.go.tz/";
const CHRAGG = "https://www.chragg.go.tz/";

const cag: NextStep = {
  office: "National Audit Office of Tanzania (CAG)",
  action:
    "Ask the Controller and Auditor General to include this site in the next LGA audit cycle and attach your observation hash.",
  actionSw:
    "Omba Mdhibiti na Mkaguzi Mkuu aingize eneo hili katika mzunguko ujao wa ukaguzi wa serikali za mitaa, na ambatanisha hash ya ushuhuda wako.",
  contact: "nao.go.tz",
  url: CAG,
  needs: ["Project name and ward", "FY and allocated amount", "Observation hash", "GPS"],
};

const pccb: NextStep = {
  office: "Prevention and Combating of Corruption Bureau",
  action: "File a report if you believe public funds were paid for work that was not done.",
  actionSw: "Wasilisha ripoti ikiwa unaamini pesa za umma zililipwa kwa kazi ambayo haikufanyika.",
  contact: "pccb.go.tz / 113",
  url: PCCB,
  needs: ["What was paid for", "What is on the ground", "Dates you visited", "No rumour: only what you saw"],
};

const councillor: NextStep = {
  office: "Ward Councillor / Local Government Authority",
  action: "Table the record in the ward: allocation, disbursement, and the last site visit.",
  actionSw: "Wasilisha rekodi katika kata: mgao, malipo, na ziara ya mwisho ya eneo.",
  contact: "LGA director, your ward",
  url: "https://www.tamisemi.go.tz/",
  needs: ["Print the project page or copy the hash", "Ask for the bill of quantities"],
};

const ati: NextStep = {
  office: "Access to Information request",
  action:
    "Request the contract, bills of quantities, payment certificates, and GPS from the procuring entity under the Access to Information Act, 2016. Appeal to CHRAGG if the clock runs out.",
  actionSw:
    "Omba mkataba, bili za kiasi, vyeti vya malipo, na GPS kutoka kwa shirika lililonunua, chini ya Sheria ya Upatikanaji wa Taarifa, 2016. Kera CHRAGG saa ikisha.",
  contact: "Accounting officer of the LGA or ministry · chragg.go.tz",
  url: CHRAGG,
  needs: ["Your postal or email address", "The exact document titles", "30 days is the statutory clock"],
};

function offices(
  region: string,
  ward: string,
  dept: string,
  deptSw: string,
): Project["responsible"] {
  return [
    {
      office: `Ward Councillor, ${ward}`,
      officeSw: `Diwani, Kata ya ${ward}`,
      duty: "Tables this project in the ward. Asks why payment ran ahead of the work on the ground.",
      dutySw: "Wasilisha mradi huu katika kata. Uliza kwa nini malipo yalikimbia mbele ya kazi ardhini.",
    },
    {
      office: `${region} LGA, ${dept}`,
      officeSw: `Serikali ya Mtaa, ${region}, ${deptSw}`,
      duty: "The procuring entity. Holds the contract, payment certificates, and the GPS the PPRA file should carry.",
      dutySw: "Shirika lililonunua. Linashikilia mkataba, vyeti vya malipo, na GPS ambayo faili la PPRA linapaswa kubeba.",
    },
    {
      office: `Regional Secretariat, ${region}`,
      officeSw: `Sekretarieti ya Mkoa, ${region}`,
      duty: "Accounting path for the region. An Access to Information request can be addressed here. This is an office, not a named person.",
      dutySw: "Njia ya uhasibu ya mkoa. Ombi la taarifa linaweza kuelekezwa hapa. Hii ni ofisi, si jina la mtu.",
    },
  ];
}

export const TZ_PROJECTS: Project[] = [
  {
    slug: "kinondoni-borehole-ii",
    name: "Kinondoni Ward Community Borehole, Phase II",
    nameSw: "Kisima cha Jamii, Kata ya Kinondoni, Awamu ya II",
    county: "Dar es Salaam",
    ward: "Kinondoni",
    sector: "water",
    status: "ghost",
    fy: "2023/24",
    allocatedKes: 18_600_000,
    disbursedKes: 18_600_000,
    contractor: "Coast Drill Works (demo name)",
    promised: "A 120-metre borehole, solar pump, 10,000-litre tank, and two communal tap stands.",
    promisedSw: "Kisima cha mita 120, pampu ya sola, tanki la lita 10,000, na vituo viwili vya bomba.",
    paperClaim: "Final certificate paid. Marked complete in the LGA implementation file.",
    paperClaimSw: "Cheti cha mwisho kililipwa. Imeandikwa imekamilika kwenye faili la utekelezaji.",
    groundNote: "Concrete pad only. No casing, no pump, no tank. Neighbours still buy from vendors.",
    groundNoteSw: "Slab ya zege tu. Hakuna bomba, pampu, wala tanki. Majirani bado wananunua kwa wachuuzi.",
    lat: -6.7924,
    lng: 39.2083,
    photo: "/evidence/borehole.jpg",
    lastOfficial: "2025-11-12",
    sources: [
      { name: "National Audit Office of Tanzania", url: CAG, published: "2025-03-31", what: "Demo patterned on water points paid in full with no yield on site." },
      { name: "Ministry of Finance", url: MOF, published: "2024-06-01", what: "LGA water capital lines." },
    ],
    nextSteps: [cag, pccb, councillor, ati],
    seedReports: 11,
    bountyKes: 8_000,
    responsible: offices("Dar es Salaam", "Kinondoni", "Water", "Maji"),
    country: "tz",
  },
  {
    slug: "ilala-drainage-lot-c",
    name: "Ilala Market Drainage, Lot C",
    nameSw: "Mifereji ya Soko la Ilala, Kundi C",
    county: "Dar es Salaam",
    ward: "Ilala",
    sector: "roads",
    status: "ghost",
    fy: "2022/23",
    allocatedKes: 42_000_000,
    disbursedKes: 42_000_000,
    contractor: "Harbour Channel Ltd (demo name)",
    promised: "Covered drain along the market lane, two silt traps, and reinstated paving.",
    promisedSw: "Mfereji uliofunikwa kando ya soko, mitego miwili ya tope, na sakafu kurejeshwa.",
    paperClaim: "Works certified complete January 2024.",
    paperClaimSw: "Kazi zilithibitishwa kuwa kamili Januari 2024.",
    groundNote: "Open trench filled with refuse. No cover slabs. Lane floods in a short rain.",
    groundNoteSw: "Mfereji wazi umejaa taka. Hakuna slabs za kufunika. Njia inafurika mvua fupi.",
    lat: -6.824,
    lng: 39.268,
    photo: "/evidence/road.jpg",
    lastOfficial: "2025-08-04",
    sources: [
      { name: "National Audit Office of Tanzania", url: CAG, published: "2025-03-31", what: "Demo of urban drainage paid ahead of cover works." },
      { name: "PPRA Tanzania", url: PPRA, published: "2024-07-01", what: "Procurement file for physical works." },
    ],
    nextSteps: [pccb, cag, councillor, ati],
    seedReports: 9,
    bountyKes: 7_000,
    responsible: offices("Dar es Salaam", "Ilala", "Works", "Kazi"),
    country: "tz",
  },
  {
    slug: "dodoma-classroom-block",
    name: "Dodoma Urban Classroom Block, Makole",
    nameSw: "Jengo la Madarasa, Makole, Dodoma Mjini",
    county: "Dodoma",
    ward: "Makole",
    sector: "education",
    status: "incomplete",
    fy: "2023/24",
    allocatedKes: 31_200_000,
    disbursedKes: 24_960_000,
    contractor: "Central Plateau Builders (demo name)",
    promised: "Four classrooms, a staff office, and pit latrines to ministry standard.",
    promisedSw: "Madarasa manne, ofisi ya walimu, na vyoo vya shimo kwa kiwango cha wizara.",
    paperClaim: "Eighty percent complete. Roofing invoiced.",
    paperClaimSw: "Asilimia 80 imekamilika. paa limeinvoisiwa.",
    groundNote: "Walls at lintel. No roof. Classes still under the tree in the dry season.",
    groundNoteSw: "Kuta ziko kimo cha lintel. Hakuna paa. Madarasa bado chini ya mti kiangazi.",
    lat: -6.163,
    lng: 35.7516,
    photo: "/evidence/classroom.jpg",
    lastOfficial: "2026-01-18",
    sources: [
      { name: "National Audit Office of Tanzania", url: CAG, published: "2025-03-31", what: "Demo of school capital paid past wall-plate with no handover." },
    ],
    nextSteps: [councillor, cag, ati],
    seedReports: 6,
    bountyKes: 5_000,
    responsible: offices("Dodoma", "Makole", "Education", "Elimu"),
    country: "tz",
  },
  {
    slug: "nyamagana-clinic-wing",
    name: "Nyamagana Health Centre Maternity Wing",
    nameSw: "Ugani wa Uzazi, Kituo cha Afya Nyamagana",
    county: "Mwanza",
    ward: "Nyamagana",
    sector: "health",
    status: "delayed",
    fy: "2024/25",
    allocatedKes: 54_000_000,
    disbursedKes: 21_600_000,
    contractor: "Lake Zone Medical Works (demo name)",
    promised: "A four-bed maternity wing, delivery room, and placenta pit.",
    promisedSw: "Ugani wa vitanda vinne vya uzazi, chumba cha kujifungua, na shimo la kondo.",
    paperClaim: "Foundation and walling in progress. First certificate paid.",
    paperClaimSw: "Msingi na kuta vinaendelea. Cheti cha kwanza kililipwa.",
    groundNote: "Foundation poured. No walls. Delivery still in the original two rooms.",
    groundNoteSw: "Msingi umemwagwa. Hakuna kuta. Uzazi bado katika vyumba viwili vya awali.",
    lat: -2.5164,
    lng: 32.917,
    photo: "/evidence/clinic.jpg",
    lastOfficial: "2026-02-09",
    sources: [
      { name: "National Audit Office of Tanzania", url: CAG, published: "2025-03-31", what: "Demo of health extensions that stall after the first certificate." },
    ],
    nextSteps: [cag, councillor, ati],
    seedReports: 4,
    bountyKes: 6_000,
    responsible: offices("Mwanza", "Nyamagana", "Health", "Afya"),
    country: "tz",
  },
  {
    slug: "arusha-street-lighting",
    name: "Arusha Central Street Lighting, Lot B",
    nameSw: "Taa za Mtaa, Arusha Kati, Kundi B",
    county: "Arusha",
    ward: "Sekei",
    sector: "energy",
    status: "ghost",
    fy: "2023/24",
    allocatedKes: 19_400_000,
    disbursedKes: 19_400_000,
    contractor: "Rift Light Poles (demo name)",
    promised: "Forty solar street lamps from the bus stand to the municipal market.",
    promisedSw: "Taa arobaini za sola kutoka stendi hadi soko la manispaa.",
    paperClaim: "Forty poles installed and commissioned.",
    paperClaimSw: "Nguzo arobaini zimewekwa na kuzinduliwa.",
    groundNote: "Twelve poles standing. Three have lamps. The market lane is dark after dusk.",
    groundNoteSw: "Nguzo kumi na mbili zimesimama. Tatu zina taa. Njia ya soko ni giza baada ya magharibi.",
    lat: -3.3869,
    lng: 36.683,
    photo: "/evidence/streetlights.jpg",
    lastOfficial: "2025-10-22",
    sources: [
      { name: "National Audit Office of Tanzania", url: CAG, published: "2025-03-31", what: "Demo of street lighting paid in full with a fraction of poles on the ground." },
    ],
    nextSteps: [pccb, cag, councillor, ati],
    seedReports: 8,
    bountyKes: 4_500,
    responsible: offices("Arusha", "Sekei", "Works", "Kazi"),
    country: "tz",
  },
  {
    slug: "mbeya-market-stalls",
    name: "Mbeya Soko Kuu Stall Block",
    nameSw: "Jengo la Maduka, Soko Kuu Mbeya",
    county: "Mbeya",
    ward: "Maendeleo",
    sector: "housing",
    status: "incomplete",
    fy: "2022/23",
    allocatedKes: 28_800_000,
    disbursedKes: 23_040_000,
    contractor: "Southern Highlands Masonry (demo name)",
    promised: "Thirty lockable stalls, a water point, and a refuse bay.",
    promisedSw: "Maduka thelathini yenye kufuli, kituo cha maji, na eneo la taka.",
    paperClaim: "Stalls at 75 percent. Water point invoiced.",
    paperClaimSw: "Maduka katika asilimia 75. Kituo cha maji kimeinvoisiwa.",
    groundNote: "Half-height walls. No doors. Traders still on tarpaulins beside the shell.",
    groundNoteSw: "Kuta nusu kimo. Hakuna milango. Wachuuzi bado kwenye tarpaulini kando ya ganda.",
    lat: -8.9094,
    lng: 33.4608,
    photo: "/evidence/market.jpg",
    lastOfficial: "2025-09-03",
    sources: [
      { name: "National Audit Office of Tanzania", url: CAG, published: "2025-03-31", what: "Demo of market stalls paid past wall-plate without handover." },
    ],
    nextSteps: [councillor, cag, ati],
    seedReports: 7,
    bountyKes: 5_500,
    responsible: offices("Mbeya", "Maendeleo", "Trade", "Biashara"),
    country: "tz",
  },
  {
    slug: "morogoro-feeder-road",
    name: "Morogoro Rural Feeder, Mkuyuni",
    nameSw: "Barabara ya Mkuyuni, Morogoro Vijijini",
    county: "Morogoro",
    ward: "Mkuyuni",
    sector: "roads",
    status: "delayed",
    fy: "2024/25",
    allocatedKes: 36_500_000,
    disbursedKes: 14_600_000,
    contractor: "Uluguru Grade Ltd (demo name)",
    promised: "Six kilometres of gravel, three drifts, and culverts before the rains.",
    promisedSw: "Kilomita sita za kokoto, vivuko vitatu, na mifereji kabla ya mvua.",
    paperClaim: "Mobilisation and first two kilometres certified.",
    paperClaimSw: "Uhamasishaji na kilomita mbili za kwanza zimethibitishwa.",
    groundNote: "Grade ends at 800 m. Culvert rings in the grass. Public footpath after the first drift.",
    groundNoteSw: "Usawazishaji unaisha baada ya mita 800. Pete za mfereji kwenye nyasi. Njia ya miguu baada ya kivuko cha kwanza.",
    lat: -6.8278,
    lng: 37.6591,
    photo: "/evidence/road.jpg",
    lastOfficial: "2026-03-01",
    sources: [
      { name: "National Audit Office of Tanzania", url: CAG, published: "2025-03-31", what: "Demo of rural feeders paid for mobilisation with the grade stopping early." },
    ],
    nextSteps: [cag, councillor, ati],
    seedReports: 5,
    bountyKes: 6_500,
    responsible: offices("Morogoro", "Mkuyuni", "Works", "Kazi"),
    country: "tz",
  },
  {
    slug: "tanga-school-lab",
    name: "Tanga Secondary School Science Lab",
    nameSw: "Maabara ya Sayansi, Shule ya Sekondari Tanga",
    county: "Tanga",
    ward: "Central",
    sector: "education",
    status: "verified",
    fy: "2023/24",
    allocatedKes: 16_800_000,
    disbursedKes: 16_800_000,
    contractor: "Coast Interiors (demo name)",
    promised: "Physics and chemistry benches, gas, sink line, and store.",
    promisedSw: "Meza za fizikia na kemia, gesi, mstari wa sinki, na stoo.",
    paperClaim: "Handed over to the school board in July 2025.",
    paperClaimSw: "Ilikabidhiwa kwa bodi ya shule Julai 2025.",
    groundNote: "Lab in the timetable. Gas and sinks work. This is what completion looks like.",
    groundNoteSw: "Maabara iko kwenye ratiba. Gesi na sinki zinafanya kazi. Hivi ndivyo ukamilifu unavyoonekana.",
    lat: -5.0689,
    lng: 39.0988,
    photo: "/evidence/lab.jpg",
    lastOfficial: "2025-08-12",
    sources: [
      { name: "Ministry of Finance", url: MOF, published: "2024-06-01", what: "Education capital lines." },
    ],
    nextSteps: [ati],
    seedReports: 3,
    bountyKes: 0,
    responsible: offices("Tanga", "Central", "Education", "Elimu"),
    country: "tz",
  },
];

export const TZ_REGIONS = [...new Set(TZ_PROJECTS.map((p) => p.county))].sort();
