import type { NextStep, Project } from "./types";

const OAG = "https://www.oagkenya.go.ke/";
const COB = "https://cob.go.ke/";
const TREASURY = "https://bajetiyetu.treasury.go.ke/";
const PPRA = "https://www.ppra.go.ke/";
const EACC = "https://eacc.go.ke/";

const oag: NextStep = {
  office: "Office of the Auditor-General",
  action: "Ask the Auditor-General to include this site in the next county audit cycle and attach your observation hash.",
  actionSw: "Omba Mkaguzi Mkuu aingize eneo hili katika mzunguko ujao wa ukaguzi wa kaunti, na ambatanisha hash ya ushuhuda wako.",
  contact: "info@oagkenya.go.ke",
  url: OAG,
  needs: ["Project name and ward", "FY and allocated amount", "Observation hash", "GPS"],
};

const eacc: NextStep = {
  office: "Ethics and Anti-Corruption Commission",
  action: "File a report if you believe public funds were paid for work that was not done.",
  actionSw: "Wasilisha ripoti ikiwa unaamini pesa za umma zililipwa kwa kazi ambayo haikufanyika.",
  contact: "report@eacc.go.ke / 1551",
  url: EACC,
  needs: ["What was paid for", "What is on the ground", "Dates you visited", "No rumour: only what you saw"],
};

const mca: NextStep = {
  office: "Ward Member of County Assembly",
  action: "Table the record in the ward: allocation, disbursement, and the last site visit.",
  actionSw: "Wasilisha rekodi katika wadi: mgao, malipo, na ziara ya mwisho ya eneo.",
  contact: "County Assembly clerk, your ward",
  url: "https://www.cog.go.ke/",
  needs: ["Print the project page or copy the hash", "Ask for the bill of quantities"],
};

const ati: NextStep = {
  office: "Access to Information request",
  action: "Request the contract, bills of quantities, payment certificates, and GPS from the procuring entity under the Access to Information Act, 2016.",
  actionSw: "Omba mkataba, bili za kiasi, vyeti vya malipo, na GPS kutoka kwa shirika lililonunua, chini ya Sheria ya Upatikanaji wa Taarifa, 2016.",
  contact: "Accounting officer of the county or ministry",
  url: "https://kenyalaw.org/kl/fileadmin/pdfdownloads/Acts/AccesstoInformationActNo31of2016.pdf",
  needs: ["Your postal or email address", "The exact document titles", "21 working days is the statutory clock"],
};

function offices(
  county: string,
  ward: string,
  dept: string,
  deptSw: string,
): Project["responsible"] {
  return [
    {
      office: `MCA, ${ward} Ward`,
      officeSw: `MCA, Wadi ya ${ward}`,
      duty: "Tables this project in the ward. Asks why payment ran ahead of the work on the ground.",
      dutySw: "Wasilisha mradi huu katika wadi. Uliza kwa nini malipo yalikimbia mbele ya kazi ardhini.",
    },
    {
      office: `${county} County Executive, ${dept}`,
      officeSw: `Mtendaji wa Kaunti ya ${county}, ${deptSw}`,
      duty: "The procuring entity. Holds the contract, payment certificates, and the GPS that PPRA now requires.",
      dutySw: "Shirika lililonunua. Linashikilia mkataba, vyeti vya malipo, na GPS ambayo PPRA sasa inahitaji.",
    },
    {
      office: `Governor, ${county} County`,
      officeSw: `Gavana, Kaunti ya ${county}`,
      duty: "Accounting officer of the county. An Access to Information request is addressed here. This is an office, not a named person.",
      dutySw: "Afisa mhasibu wa kaunti. Ombi la taarifa linaelekezwa hapa. Hii ni ofisi, si jina la mtu.",
    },
  ];
}

export const PROJECTS: Project[] = [
  {
    slug: "langata-borehole-ii",
    name: "Lang'ata Ward Community Borehole, Phase II",
    nameSw: "Kisima cha Jamii, Wadi ya Lang'ata, Awamu ya II",
    county: "Nairobi",
    ward: "Lang'ata",
    sector: "water",
    status: "ghost",
    fy: "2023/24",
    allocatedKes: 12_400_000,
    disbursedKes: 11_160_000,
    contractor: "Savanna Civils Ltd (demo name)",
    promised: "A 140-metre borehole, solar pump, 10,000-litre tank, and cattle trough.",
    promisedSw: "Kisima cha mita 140, pampu ya sola, tanki la lita 10,000, na kiorosho cha mifugo.",
    paperClaim: "Payment certificate 3 of 3 marked complete in May 2024.",
    paperClaimSw: "Cheti cha malipo 3 kati ya 3 kimeandikwa kuwa kazi imekamilika Mei 2024.",
    groundNote: "Concrete pad and a capped pipe. No pump, no tank, no water. Grass through the slab.",
    groundNoteSw: "Slab ya zege na bomba lililofungwa. Hakuna pampu, tanki, wala maji. Nyasi zimepita kwenye slab.",
    lat: -1.3662,
    lng: 36.7374,
    photo: "/evidence/borehole.jpg",
    lastOfficial: "2025-11-02",
    sources: [
      { name: "Auditor-General (county pattern)", url: OAG, published: "2025-06-30", what: "Demo row patterned on OAG findings of water projects paid but not found on site." },
      { name: "Controller of Budget", url: COB, published: "2025-08-15", what: "County budget implementation reports list water development lines." },
      { name: "Bajeti Yetu", url: TREASURY, published: "2026-09-01", what: "National and county budget document portal." },
    ],
    nextSteps: [eacc, oag, mca, ati],
    seedReports: 14,
    bountyKes: 6_000,
    responsible: offices("Nairobi", "Lang'ata", "Water and Sanitation", "Maji na Usafi"),
  },
  {
    slug: "nyalenda-market-shades",
    name: "Nyalenda Market Shade Upgrade",
    nameSw: "Uboreshaji wa Vivuli vya Soko la Nyalenda",
    county: "Kisumu",
    ward: "Nyalenda B",
    sector: "housing",
    status: "incomplete",
    fy: "2024/25",
    allocatedKes: 48_750_000,
    disbursedKes: 43_900_000,
    contractor: "Lake Basin Works (demo name)",
    promised: "Steel shade over 220 stalls, drainage, and three ablution blocks.",
    promisedSw: "Kivuli cha chuma juu ya maduka 220, mifereji, na vyoo vitatu.",
    paperClaim: "90 percent disbursed. Progress report says 85 percent complete.",
    paperClaimSw: "Asilimia 90 imelipwa. Ripoti ya maendeleo inasema asilimia 85 imekamilika.",
    groundNote: "Columns are up on one wing. Two wings are open sky. Ablution slab only.",
    groundNoteSw: "Nguzo zimesimama upande mmoja. Pande mbili ni wazi. Slab ya vyoo tu.",
    lat: -0.1204,
    lng: 34.7681,
    photo: "/evidence/market.jpg",
    lastOfficial: "2026-03-12",
    sources: [
      { name: "Controller of Budget", url: COB, published: "2026-02-28", what: "Demo: high disbursement against incomplete physical works is a recurring CoB flag." },
      { name: "PPRA e-GPS", url: PPRA, published: "2025-07-01", what: "GPS on tenders is now required to stop duplicate ghost sites." },
    ],
    nextSteps: [mca, oag, ati],
    seedReports: 9,
    bountyKes: 5_000,
    responsible: offices("Kisumu", "Nyalenda B", "Lands, Housing and Urban Development", "Ardhi, Nyumba na Miji"),
  },
  {
    slug: "likoni-ecd-classrooms",
    name: "Likoni ECD Twin Classroom",
    nameSw: "Madarasa Mapacha ya ECD Likoni",
    county: "Mombasa",
    ward: "Likoni",
    sector: "education",
    status: "verified",
    fy: "2022/23",
    allocatedKes: 9_800_000,
    disbursedKes: 9_800_000,
    contractor: "Coastal Build Group (demo name)",
    promised: "Two classrooms, office, rainwater tank, and pit latrines.",
    promisedSw: "Madarasa mawili, ofisi, tanki la mvua, na vyoo.",
    paperClaim: "Certificate of completion issued January 2024.",
    paperClaimSw: "Cheti cha kukamilika kilitolewa Januari 2024.",
    groundNote: "Building in use. Roof, desks, and tank present. Eight independent visits agree.",
    groundNoteSw: "Jengo linatumika. Paa, madawati, na tanki vipo. Ziara nane za kujitegemea zinakubaliana.",
    lat: -4.0851,
    lng: 39.6619,
    photo: "/evidence/classroom-done.jpg",
    lastOfficial: "2026-01-20",
    sources: [
      { name: "County CIDP extracts via Bajeti Yetu", url: TREASURY, published: "2024-06-01", what: "Demo completion against a published education line." },
    ],
    nextSteps: [ati],
    seedReports: 8,
    bountyKes: 0,
    responsible: offices("Mombasa", "Likoni", "Education", "Elimu"),
  },
  {
    slug: "kakuma-staff-houses",
    name: "Kakuma Health Centre Staff Houses",
    nameSw: "Nyumba za Wafanyakazi, Kituo cha Afya Kakuma",
    county: "Turkana",
    ward: "Kakuma",
    sector: "health",
    status: "ghost",
    fy: "2023/24",
    allocatedKes: 36_200_000,
    disbursedKes: 28_960_000,
    contractor: "North Rift Shelters (demo name)",
    promised: "Six two-room staff houses with solar and pit latrines, to keep clinicians on site.",
    promisedSw: "Nyumba sita za vyumba viwili kwa wafanyakazi, sola na vyoo, ili wahudumu wabaki kituoni.",
    paperClaim: "Four units certified complete. Two listed as ongoing.",
    paperClaimSw: "Vitengo vinne vimeshuhudiwa kuwa vimekamilika. Viwili vimeandikwa vinaendelea.",
    groundNote: "Empty plot beside the existing clinic. No foundations. Neighbours say the contractor never camped.",
    groundNoteSw: "Kiwanja tupu kando ya kituo kilichopo. Hakuna misingi. Majirani wanasema mkandarasi hakuwahi kupiga kambi.",
    lat: 3.7172,
    lng: 34.8503,
    photo: "/evidence/empty-plot.jpg",
    lastOfficial: "2025-09-18",
    sources: [
      { name: "Auditor-General", url: OAG, published: "2025-06-30", what: "Demo patterned on staff-housing lines paid without buildings on site." },
      { name: "Controller of Budget", url: COB, published: "2025-11-01", what: "Health development expenditure in arid counties." },
    ],
    nextSteps: [eacc, oag, mca, ati],
    seedReports: 11,
    bountyKes: 9_000,
    responsible: offices("Turkana", "Kakuma", "Health and Sanitation", "Afya na Usafi"),
  },
  {
    slug: "kaptembwo-imaging-wing",
    name: "Kaptembwo Hospital Imaging Wing",
    nameSw: "Wingo ya Picha, Hospitali ya Kaptembwo",
    county: "Nakuru",
    ward: "Kaptembwo",
    sector: "health",
    status: "delayed",
    fy: "2021/22",
    allocatedKes: 112_000_000,
    disbursedKes: 67_200_000,
    contractor: "Rift Works Contractors (demo name)",
    promised: "X-ray and ultrasound rooms, backup power, and a waiting bay.",
    promisedSw: "Vyumba vya eksirei na ultrasound, umeme wa chelezo, na eneo la kusubiri.",
    paperClaim: "Contract extended three times. Latest completion date: June 2026.",
    paperClaimSw: "Mkataba umeongezwa mara tatu. Tarehe mpya ya kukamilika: Juni 2026.",
    groundNote: "Shell has been standing since 2023. No equipment. Roof sheets partly on.",
    groundNoteSw: "Gamba limesimama tangu 2023. Hakuna vifaa. Laha za paa zimewekwa sehemu.",
    lat: -0.3034,
    lng: 36.0661,
    photo: "/evidence/clinic.jpg",
    lastOfficial: "2026-04-02",
    sources: [
      { name: "Controller of Budget", url: COB, published: "2026-02-28", what: "Demo of multi-year stalled health capital projects." },
      { name: "PPRA", url: PPRA, published: "2025-07-01", what: "Contract variation and GPS rules." },
    ],
    nextSteps: [mca, oag, ati],
    seedReports: 6,
    bountyKes: 4_500,
    responsible: offices("Nakuru", "Kaptembwo", "Health", "Afya"),
  },
  {
    slug: "lurambi-feeder-road",
    name: "Lurambi Feeder Road 4.2 km",
    nameSw: "Barabara ya Lurambi, km 4.2",
    county: "Kakamega",
    ward: "Lurambi",
    sector: "roads",
    status: "ghost",
    fy: "2024/25",
    allocatedKes: 64_500_000,
    disbursedKes: 64_500_000,
    contractor: "Western Grade Ltd (demo name)",
    promised: "Gravel standard, culverts at three crossings, 4.2 km gazetted alignment.",
    promisedSw: "Kiwango cha kokoto, mirongo katika vivuko vitatu, km 4.2 kwenye mpangilio uliochapishwa.",
    paperClaim: "Full contract value paid. Same alignment also appears in a national roads batch.",
    paperClaimSw: "Thamani yote ya mkataba imelipwa. Mpangilio huohuo unaonekana pia kwenye kundi la barabara za kitaifa.",
    groundNote: "Grade stops after 700 metres. Culvert rings in the grass. The rest is a footpath.",
    groundNoteSw: "Uso wa barabara unaishia baada ya mita 700. Mirongo chini ya nyasi. Ilongezwa ni njia ya miguu.",
    lat: 0.2821,
    lng: 34.7522,
    photo: "/evidence/road.jpg",
    lastOfficial: "2026-05-11",
    sources: [
      { name: "PPRA e-GPS", url: PPRA, published: "2025-07-01", what: "Demo of the duplicate-allocation problem GPS on tenders was meant to kill." },
      { name: "Auditor-General", url: OAG, published: "2025-06-30", what: "Pattern: road paid twice across county and national lines." },
    ],
    nextSteps: [eacc, oag, mca, ati],
    seedReports: 17,
    bountyKes: 12_000,
    responsible: offices("Kakamega", "Lurambi", "Roads and Public Works", "Barabara na Kazi za Umma"),
  },
  {
    slug: "malindi-sanitation-block",
    name: "Malindi Primary Sanitation Block",
    nameSw: "Kizuizi cha Usafi, Primary ya Malindi",
    county: "Kilifi",
    ward: "Malindi Town",
    sector: "education",
    status: "incomplete",
    fy: "2023/24",
    allocatedKes: 4_600_000,
    disbursedKes: 4_140_000,
    contractor: "Reef Line Builders (demo name)",
    promised: "Eight-door pit latrine, disability stall, handwashing trough.",
    promisedSw: "Choo cha milango minane, stesheni ya walemavu, kiorosho cha kunawa.",
    paperClaim: "Marked substantially complete.",
    paperClaimSw: "Imeandikwa kuwa imekamilika kwa kiasi kikubwa.",
    groundNote: "Walls up, no roof, no doors, pit not lined. Children still use the old block.",
    groundNoteSw: "Kuta zipo, hakuna paa, hakuna milango, shimo halijafunikwa. Watoto bado wanatumia kizuizi cha zamani.",
    lat: -3.2189,
    lng: 40.1167,
    photo: "/evidence/latrine.jpg",
    lastOfficial: "2025-10-08",
    sources: [
      { name: "Bajeti Yetu", url: TREASURY, published: "2024-09-01", what: "Education development lines at county level." },
      { name: "Auditor-General", url: OAG, published: "2025-06-30", what: "Demo: sanitation blocks paid as complete while unusable." },
    ],
    nextSteps: [mca, oag, ati],
    seedReports: 5,
    bountyKes: 3_000,
    responsible: offices("Kilifi", "Malindi Town", "Education", "Elimu"),
  },
  {
    slug: "dadaab-water-pan",
    name: "Dadaab Water Pan Rehabilitation",
    nameSw: "Ukarabati wa Dimba la Maji, Dadaab",
    county: "Garissa",
    ward: "Dadaab",
    sector: "water",
    status: "verified",
    fy: "2022/23",
    allocatedKes: 18_300_000,
    disbursedKes: 17_400_000,
    contractor: "Harambee Earthworks (demo name)",
    promised: "Desilt 40,000 cubic metres, fence, cattle trough, silt trap.",
    promisedSw: "Ondoa tope mita za ujazo 40,000, uzio, kiorosho cha mifugo, mtego wa tope.",
    paperClaim: "Practical completion November 2023.",
    paperClaimSw: "Ukamilishaji wa kimatendo Novemba 2023.",
    groundNote: "Pan holds water after rains. Fence and trough in place. Community water-user group confirmed.",
    groundNoteSw: "Dimba linashikilia maji baada ya mvua. Uzio na kiorosho vipo. Kikundi cha watumiaji maji kimethibitisha.",
    lat: 0.0534,
    lng: 40.3189,
    photo: "/evidence/waterpan.jpg",
    lastOfficial: "2025-12-04",
    sources: [
      { name: "Controller of Budget", url: COB, published: "2024-08-30", what: "Demo of a water pan that did reach the ground." },
    ],
    nextSteps: [ati],
    seedReports: 7,
    bountyKes: 0,
    responsible: offices("Garissa", "Dadaab", "Water", "Maji"),
  },
  {
    slug: "kayole-lighting-b",
    name: "Kayole Street Lighting Lot B",
    nameSw: "Taa za Mitaani Kayole, Kundi B",
    county: "Nairobi",
    ward: "Kayole South",
    sector: "energy",
    status: "delayed",
    fy: "2024/25",
    allocatedKes: 22_750_000,
    disbursedKes: 9_100_000,
    contractor: "Metro Poles KE (demo name)",
    promised: "180 solar street lights along the spine road and market lane.",
    promisedSw: "Taa 180 za sola kwenye barabara kuu na njia ya soko.",
    paperClaim: "Forty poles erected. Balance awaiting imported fixtures.",
    paperClaimSw: "Nguzo arobaini zimesimamishwa. Salio linasubiri vifaa vilivyoagizwa nje.",
    groundNote: "Twenty-two poles standing, twelve of them dark. No lamps on the market lane.",
    groundNoteSw: "Nguzo ishirini na mbili zimesimama, kumi na mbili ni giza. Hakuna taa kwenye njia ya soko.",
    lat: -1.2754,
    lng: 36.9072,
    photo: "/evidence/streetlights.jpg",
    lastOfficial: "2026-06-19",
    sources: [
      { name: "Nairobi County budget documents", url: TREASURY, published: "2025-06-01", what: "Street lighting is a high-visibility line that still slips." },
    ],
    nextSteps: [mca, oag, ati],
    seedReports: 12,
    bountyKes: 3_500,
    responsible: offices("Nairobi", "Kayole South", "Energy and Lighting", "Nishati na Taa"),
  },
  {
    slug: "mathare-dispensary-ext",
    name: "Mathare North Dispensary Extension",
    nameSw: "Ugani wa Zahanati, Mathare Kaskazini",
    county: "Nairobi",
    ward: "Mabatini",
    sector: "health",
    status: "incomplete",
    fy: "2023/24",
    allocatedKes: 15_600_000,
    disbursedKes: 12_480_000,
    contractor: "Eastlands Masonry (demo name)",
    promised: "Two extra consultation rooms, pharmacy cage, and waiting shelter.",
    promisedSw: "Vyumba viwili vya ziada vya ushauri, cage ya duka la dawa, na kivuli cha kusubiri.",
    paperClaim: "Works at 70 percent. Pharmacy fittings invoiced.",
    paperClaimSw: "Kazi katika asilimia 70. Vifaa vya duka la dawa vimeinvoisiwa.",
    groundNote: "Extension walls at window height. Clinic still runs from the original two rooms.",
    groundNoteSw: "Kuta za ugani ziko kimo cha dirisha. Zahanati bado inafanya kazi kutoka vyumba viwili vya awali.",
    lat: -1.2594,
    lng: 36.8581,
    photo: "/evidence/dispensary.jpg",
    lastOfficial: "2026-02-14",
    sources: [
      { name: "Auditor-General", url: OAG, published: "2025-06-30", what: "Demo of urban health extensions that stall at wall-plate." },
    ],
    nextSteps: [mca, oag, eacc, ati],
    seedReports: 10,
    bountyKes: 4_000,
    responsible: offices("Nairobi", "Mabatini", "Health", "Afya"),
  },
  {
    slug: "kiambu-high-school-lab",
    name: "Kiambu High School Science Lab",
    nameSw: "Maabara ya Sayansi, Kiambu High",
    county: "Kiambu",
    ward: "Township",
    sector: "education",
    status: "verified",
    fy: "2023/24",
    allocatedKes: 14_200_000,
    disbursedKes: 14_200_000,
    contractor: "Ridge Line Interiors (demo name)",
    promised: "Physics and chemistry benches, gas, sink line, and store.",
    promisedSw: "Meza za fizikia na kemia, gesi, mstari wa sinki, na stoo.",
    paperClaim: "Handed over to the school board in August 2025.",
    paperClaimSw: "Ilikabidhiwa kwa bodi ya shule Agosti 2025.",
    groundNote: "Lab in the timetable. Gas and sinks work. This is what completion looks like.",
    groundNoteSw: "Maabara iko kwenye ratiba. Gesi na sinki zinafanya kazi. Hivi ndivyo ukamilifu unavyoonekana.",
    lat: -1.1712,
    lng: 36.8354,
    photo: "/evidence/lab.jpg",
    lastOfficial: "2025-09-01",
    sources: [
      { name: "Bajeti Yetu", url: TREASURY, published: "2024-06-01", what: "NG-CDF / county education capital lines." },
    ],
    nextSteps: [ati],
    seedReports: 4,
    bountyKes: 0,
    responsible: offices("Kiambu", "Township", "Education", "Elimu"),
  },
  {
    slug: "kitui-earth-dam",
    name: "Kitui Rural Earth Dam, Zone 4",
    nameSw: "Bwawa la Udongo, Kitui Kijijini, Eneo 4",
    county: "Kitui",
    ward: "Kisasi",
    sector: "water",
    status: "ghost",
    fy: "2022/23",
    allocatedKes: 27_800_000,
    disbursedKes: 27_800_000,
    contractor: "Ukambani Water Works (demo name)",
    promised: "Excavation of 80,000 cubic metres, spillway, and communal tap stand.",
    promisedSw: "Uchimbaji wa mita za ujazo 80,000, njia ya mafuriko, na kituo cha bomba cha jamii.",
    paperClaim: "Final certificate paid December 2023.",
    paperClaimSw: "Cheti cha mwisho kililipwa Desemba 2023.",
    groundNote: "Shallow scrape. No spillway. No tap. Livestock still walk 6 km in the dry season.",
    groundNoteSw: "Kukwangua kijuujuu. Hakuna njia ya mafuriko. Hakuna bomba. Mifugo bado inatembea km 6 wakati wa kiangazi.",
    lat: -1.3911,
    lng: 38.0102,
    photo: "/evidence/dam.jpg",
    lastOfficial: "2025-07-22",
    sources: [
      { name: "Auditor-General", url: OAG, published: "2025-06-30", what: "Demo patterned on earth dams paid in full with negligible storage." },
      { name: "Controller of Budget", url: COB, published: "2024-08-30", what: "Water and irrigation development in Kitui." },
    ],
    nextSteps: [eacc, oag, mca, ati],
    seedReports: 13,
    bountyKes: 8_000,
    responsible: offices("Kitui", "Kisasi", "Water", "Maji"),
  },
];

export const COUNTIES = [...new Set(PROJECTS.map((p) => p.county))].sort();
export const SECTORS: Project["sector"][] = [
  "water",
  "health",
  "education",
  "roads",
  "energy",
  "housing",
];

export const DEMO_BANNER =
  "These records are a working proof of concept. Amounts, bounties, and site notes are illustrative composites patterned on published Auditor-General and Controller of Budget problems. They are not live IFMIS extracts. Offices are named, not people. Contractor names are labelled as demo names.";
