/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ActRouteImport } from './routes/act'
import { Route as BountiesRouteImport } from './routes/bounties'
import { Route as ClockRouteImport } from './routes/clock'
import { Route as LedgerRouteImport } from './routes/ledger'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MethodRouteImport } from './routes/method'
import { Route as NamedRouteImport } from './routes/named'
import { Route as RecordRouteImport } from './routes/record'
import { Route as ReportRouteImport } from './routes/report'
import { Route as SafeRouteImport } from './routes/safe'
import { Route as TourRouteImport } from './routes/tour'
import { Route as BountiesIndexRouteImport } from './routes/bounties.index'
import { Route as BountiesIdRouteImport } from './routes/bounties.$id'
import { Route as BountiesNewRouteImport } from './routes/bounties.new'
import { Route as LedgerSlugRouteImport } from './routes/ledger.$slug'
import { Route as TourIndexRouteImport } from './routes/tour.index'
import { Route as TourIdRouteImport } from './routes/tour.$id'
import { Route as TourNewRouteImport } from './routes/tour.new'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ActRoute = ActRouteImport.update({
  id: '/act',
  path: '/act',
  getParentRoute: () => rootRouteImport,
} as any)
const BountiesRoute = BountiesRouteImport.update({
  id: '/bounties',
  path: '/bounties',
  getParentRoute: () => rootRouteImport,
} as any)
const ClockRoute = ClockRouteImport.update({
  id: '/clock',
  path: '/clock',
  getParentRoute: () => rootRouteImport,
} as any)
const LedgerRoute = LedgerRouteImport.update({
  id: '/ledger',
  path: '/ledger',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MethodRoute = MethodRouteImport.update({
  id: '/method',
  path: '/method',
  getParentRoute: () => rootRouteImport,
} as any)
const NamedRoute = NamedRouteImport.update({
  id: '/named',
  path: '/named',
  getParentRoute: () => rootRouteImport,
} as any)
const RecordRoute = RecordRouteImport.update({
  id: '/record',
  path: '/record',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportRoute = ReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => rootRouteImport,
} as any)
const SafeRoute = SafeRouteImport.update({
  id: '/safe',
  path: '/safe',
  getParentRoute: () => rootRouteImport,
} as any)
const TourRoute = TourRouteImport.update({
  id: '/tour',
  path: '/tour',
  getParentRoute: () => rootRouteImport,
} as any)
const BountiesIndexRoute = BountiesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BountiesRoute,
} as any)
const BountiesIdRoute = BountiesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => BountiesRoute,
} as any)
const BountiesNewRoute = BountiesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => BountiesRoute,
} as any)
const LedgerSlugRoute = LedgerSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => LedgerRoute,
} as any)
const TourIndexRoute = TourIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TourRoute,
} as any)
const TourIdRoute = TourIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => TourRoute,
} as any)
const TourNewRoute = TourNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => TourRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/act': typeof ActRoute
  '/bounties': typeof BountiesRouteWithChildren
  '/clock': typeof ClockRoute
  '/ledger': typeof LedgerRouteWithChildren
  '/login': typeof LoginRoute
  '/method': typeof MethodRoute
  '/named': typeof NamedRoute
  '/record': typeof RecordRoute
  '/report': typeof ReportRoute
  '/safe': typeof SafeRoute
  '/tour': typeof TourRouteWithChildren
  '/bounties/$id': typeof BountiesIdRoute
  '/bounties/new': typeof BountiesNewRoute
  '/ledger/$slug': typeof LedgerSlugRoute
  '/tour/$id': typeof TourIdRoute
  '/tour/new': typeof TourNewRoute
  '/bounties/': typeof BountiesIndexRoute
  '/tour/': typeof TourIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/act': typeof ActRoute
  '/clock': typeof ClockRoute
  '/ledger': typeof LedgerRouteWithChildren
  '/login': typeof LoginRoute
  '/method': typeof MethodRoute
  '/named': typeof NamedRoute
  '/record': typeof RecordRoute
  '/report': typeof ReportRoute
  '/safe': typeof SafeRoute
  '/bounties/$id': typeof BountiesIdRoute
  '/bounties/new': typeof BountiesNewRoute
  '/ledger/$slug': typeof LedgerSlugRoute
  '/tour/$id': typeof TourIdRoute
  '/tour/new': typeof TourNewRoute
  '/bounties': typeof BountiesIndexRoute
  '/tour': typeof TourIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/act': typeof ActRoute
  '/bounties': typeof BountiesRouteWithChildren
  '/clock': typeof ClockRoute
  '/ledger': typeof LedgerRouteWithChildren
  '/login': typeof LoginRoute
  '/method': typeof MethodRoute
  '/named': typeof NamedRoute
  '/record': typeof RecordRoute
  '/report': typeof ReportRoute
  '/safe': typeof SafeRoute
  '/tour': typeof TourRouteWithChildren
  '/bounties/$id': typeof BountiesIdRoute
  '/bounties/new': typeof BountiesNewRoute
  '/ledger/$slug': typeof LedgerSlugRoute
  '/tour/$id': typeof TourIdRoute
  '/tour/new': typeof TourNewRoute
  '/bounties/': typeof BountiesIndexRoute
  '/tour/': typeof TourIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/act'
    | '/bounties'
    | '/clock'
    | '/ledger'
    | '/login'
    | '/method'
    | '/named'
    | '/record'
    | '/report'
    | '/safe'
    | '/tour'
    | '/bounties/$id'
    | '/bounties/new'
    | '/ledger/$slug'
    | '/tour/$id'
    | '/tour/new'
    | '/bounties/'
    | '/tour/'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/act'
    | '/clock'
    | '/ledger'
    | '/login'
    | '/method'
    | '/named'
    | '/record'
    | '/report'
    | '/safe'
    | '/bounties/$id'
    | '/bounties/new'
    | '/ledger/$slug'
    | '/tour/$id'
    | '/tour/new'
    | '/bounties'
    | '/tour'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/act'
    | '/bounties'
    | '/clock'
    | '/ledger'
    | '/login'
    | '/method'
    | '/named'
    | '/record'
    | '/report'
    | '/safe'
    | '/tour'
    | '/bounties/$id'
    | '/bounties/new'
    | '/ledger/$slug'
    | '/tour/$id'
    | '/tour/new'
    | '/bounties/'
    | '/tour/'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ActRoute: typeof ActRoute
  BountiesRoute: typeof BountiesRouteWithChildren
  ClockRoute: typeof ClockRoute
  LedgerRoute: typeof LedgerRouteWithChildren
  LoginRoute: typeof LoginRoute
  MethodRoute: typeof MethodRoute
  NamedRoute: typeof NamedRoute
  RecordRoute: typeof RecordRoute
  ReportRoute: typeof ReportRoute
  SafeRoute: typeof SafeRoute
  TourRoute: typeof TourRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/act': {
      id: '/act'
      path: '/act'
      fullPath: '/act'
      preLoaderRoute: typeof ActRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bounties': {
      id: '/bounties'
      path: '/bounties'
      fullPath: '/bounties'
      preLoaderRoute: typeof BountiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clock': {
      id: '/clock'
      path: '/clock'
      fullPath: '/clock'
      preLoaderRoute: typeof ClockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ledger': {
      id: '/ledger'
      path: '/ledger'
      fullPath: '/ledger'
      preLoaderRoute: typeof LedgerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/method': {
      id: '/method'
      path: '/method'
      fullPath: '/method'
      preLoaderRoute: typeof MethodRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/named': {
      id: '/named'
      path: '/named'
      fullPath: '/named'
      preLoaderRoute: typeof NamedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/record': {
      id: '/record'
      path: '/record'
      fullPath: '/record'
      preLoaderRoute: typeof RecordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report': {
      id: '/report'
      path: '/report'
      fullPath: '/report'
      preLoaderRoute: typeof ReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/safe': {
      id: '/safe'
      path: '/safe'
      fullPath: '/safe'
      preLoaderRoute: typeof SafeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tour': {
      id: '/tour'
      path: '/tour'
      fullPath: '/tour'
      preLoaderRoute: typeof TourRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bounties/': {
      id: '/bounties/'
      path: '/'
      fullPath: '/bounties/'
      preLoaderRoute: typeof BountiesIndexRouteImport
      parentRoute: typeof BountiesRoute
    }
    '/bounties/$id': {
      id: '/bounties/$id'
      path: '/$id'
      fullPath: '/bounties/$id'
      preLoaderRoute: typeof BountiesIdRouteImport
      parentRoute: typeof BountiesRoute
    }
    '/bounties/new': {
      id: '/bounties/new'
      path: '/new'
      fullPath: '/bounties/new'
      preLoaderRoute: typeof BountiesNewRouteImport
      parentRoute: typeof BountiesRoute
    }
    '/ledger/$slug': {
      id: '/ledger/$slug'
      path: '/$slug'
      fullPath: '/ledger/$slug'
      preLoaderRoute: typeof LedgerSlugRouteImport
      parentRoute: typeof LedgerRoute
    }
    '/tour/': {
      id: '/tour/'
      path: '/'
      fullPath: '/tour/'
      preLoaderRoute: typeof TourIndexRouteImport
      parentRoute: typeof TourRoute
    }
    '/tour/$id': {
      id: '/tour/$id'
      path: '/$id'
      fullPath: '/tour/$id'
      preLoaderRoute: typeof TourIdRouteImport
      parentRoute: typeof TourRoute
    }
    '/tour/new': {
      id: '/tour/new'
      path: '/new'
      fullPath: '/tour/new'
      preLoaderRoute: typeof TourNewRouteImport
      parentRoute: typeof TourRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface BountiesRouteChildren {
  BountiesIdRoute: typeof BountiesIdRoute
  BountiesNewRoute: typeof BountiesNewRoute
  BountiesIndexRoute: typeof BountiesIndexRoute
}

const BountiesRouteChildren: BountiesRouteChildren = {
  BountiesIdRoute: BountiesIdRoute,
  BountiesNewRoute: BountiesNewRoute,
  BountiesIndexRoute: BountiesIndexRoute,
}

const BountiesRouteWithChildren = BountiesRoute._addFileChildren(
  BountiesRouteChildren,
)

interface LedgerRouteChildren {
  LedgerSlugRoute: typeof LedgerSlugRoute
}

const LedgerRouteChildren: LedgerRouteChildren = {
  LedgerSlugRoute: LedgerSlugRoute,
}

const LedgerRouteWithChildren =
  LedgerRoute._addFileChildren(LedgerRouteChildren)

interface TourRouteChildren {
  TourIdRoute: typeof TourIdRoute
  TourNewRoute: typeof TourNewRoute
  TourIndexRoute: typeof TourIndexRoute
}

const TourRouteChildren: TourRouteChildren = {
  TourIdRoute: TourIdRoute,
  TourNewRoute: TourNewRoute,
  TourIndexRoute: TourIndexRoute,
}

const TourRouteWithChildren = TourRoute._addFileChildren(TourRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ActRoute: ActRoute,
  BountiesRoute: BountiesRouteWithChildren,
  ClockRoute: ClockRoute,
  LedgerRoute: LedgerRouteWithChildren,
  LoginRoute: LoginRoute,
  MethodRoute: MethodRoute,
  NamedRoute: NamedRoute,
  RecordRoute: RecordRoute,
  ReportRoute: ReportRoute,
  SafeRoute: SafeRoute,
  TourRoute: TourRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
